function TSynWebEngine.CssPropUndef: TSynWebTokenKind;
begin
  Result:=stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc29: TSynWebTokenKind;
begin
  if  CssPropKeyComp(37) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc39: TSynWebTokenKind;
begin
  if  CssPropKeyComp(31) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc40: TSynWebTokenKind;
begin
  if  CssPropKeyComp(32) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc43: TSynWebTokenKind;
begin
  if  CssPropKeyComp(53) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc51: TSynWebTokenKind;
begin
  if  CssPropKeyComp(104) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc52: TSynWebTokenKind;
begin
  if  CssPropKeyComp(93) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc54: TSynWebTokenKind;
begin
  if  CssPropKeyComp(45) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc55: TSynWebTokenKind;
begin
  if  CssPropKeyComp(46) or
      CssPropKeyComp(75) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc56: TSynWebTokenKind;
begin
  if  CssPropKeyComp(86) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc57: TSynWebTokenKind;
begin
  if  CssPropKeyComp(52) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc62: TSynWebTokenKind;
begin
  if  CssPropKeyComp(7) or
      CssPropKeyComp(60) or
      CssPropKeyComp(83) or
      CssPropKeyComp(92) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc63: TSynWebTokenKind;
begin
  if  CssPropKeyComp(33) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc64: TSynWebTokenKind;
begin
  if  CssPropKeyComp(112) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc85: TSynWebTokenKind;
begin
  if  CssPropKeyComp(29) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc86: TSynWebTokenKind;
begin
  if  CssPropKeyComp(42) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc88: TSynWebTokenKind;
begin
  if  CssPropKeyComp(109) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc91: TSynWebTokenKind;
begin
  if  CssPropKeyComp(34) or
      CssPropKeyComp(69) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc93: TSynWebTokenKind;
begin
  if  CssPropKeyComp(111) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc94: TSynWebTokenKind;
begin
  if  CssPropKeyComp(40) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc95: TSynWebTokenKind;
begin
  if  CssPropKeyComp(91) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc96: TSynWebTokenKind;
begin
  if  CssPropKeyComp(1) or
      CssPropKeyComp(70) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc97: TSynWebTokenKind;
begin
  if  CssPropKeyComp(41) or
      CssPropKeyComp(90) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc98: TSynWebTokenKind;
begin
  if  CssPropKeyComp(0) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc100: TSynWebTokenKind;
begin
  if  CssPropKeyComp(98) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc103: TSynWebTokenKind;
begin
  if  CssPropKeyComp(43) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc116: TSynWebTokenKind;
begin
  if  CssPropKeyComp(74) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc117: TSynWebTokenKind;
begin
  if  CssPropKeyComp(38) or
      CssPropKeyComp(89) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc118: TSynWebTokenKind;
begin
  if  CssPropKeyComp(39) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc120: TSynWebTokenKind;
begin
  if  CssPropKeyComp(114) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc131: TSynWebTokenKind;
begin
  if  CssPropKeyComp(67) or
      CssPropKeyComp(94) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc133: TSynWebTokenKind;
begin
  if  CssPropKeyComp(65) or
      CssPropKeyComp(105) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc135: TSynWebTokenKind;
begin
  if  CssPropKeyComp(55) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc136: TSynWebTokenKind;
begin
  if  CssPropKeyComp(77) or
      CssPropKeyComp(107) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc138: TSynWebTokenKind;
begin
  if  CssPropKeyComp(68) or
      CssPropKeyComp(97) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc139: TSynWebTokenKind;
begin
  if  CssPropKeyComp(87) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc140: TSynWebTokenKind;
begin
  if  CssPropKeyComp(66) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc143: TSynWebTokenKind;
begin
  if  CssPropKeyComp(14) or
      CssPropKeyComp(62) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc144: TSynWebTokenKind;
begin
  if  CssPropKeyComp(79) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc147: TSynWebTokenKind;
begin
  if  CssPropKeyComp(110) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc150: TSynWebTokenKind;
begin
  if  CssPropKeyComp(84) or
      CssPropKeyComp(100) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc151: TSynWebTokenKind;
begin
  if  CssPropKeyComp(24) or
      CssPropKeyComp(64) or
      CssPropKeyComp(85) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc152: TSynWebTokenKind;
begin
  if  CssPropKeyComp(48) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc153: TSynWebTokenKind;
begin
  if  CssPropKeyComp(30) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc155: TSynWebTokenKind;
begin
  if  CssPropKeyComp(78) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc158: TSynWebTokenKind;
begin
  if  CssPropKeyComp(108) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc159: TSynWebTokenKind;
begin
  if  CssPropKeyComp(47) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc162: TSynWebTokenKind;
begin
  if  CssPropKeyComp(18) or
      CssPropKeyComp(63) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc163: TSynWebTokenKind;
begin
  if  CssPropKeyComp(13) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc164: TSynWebTokenKind;
begin
  if  CssPropKeyComp(28) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc165: TSynWebTokenKind;
begin
  if  CssPropKeyComp(51) or
      CssPropKeyComp(88) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc167: TSynWebTokenKind;
begin
  if  CssPropKeyComp(113) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc168: TSynWebTokenKind;
begin
  if  CssPropKeyComp(44) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc169: TSynWebTokenKind;
begin
  if  CssPropKeyComp(4) or
      CssPropKeyComp(22) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc171: TSynWebTokenKind;
begin
  if  CssPropKeyComp(106) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc172: TSynWebTokenKind;
begin
  if  CssPropKeyComp(99) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc173: TSynWebTokenKind;
begin
  if  CssPropKeyComp(102) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc174: TSynWebTokenKind;
begin
  if  CssPropKeyComp(49) or
      CssPropKeyComp(95) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc178: TSynWebTokenKind;
begin
  if  CssPropKeyComp(50) or
      CssPropKeyComp(76) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc179: TSynWebTokenKind;
begin
  if  CssPropKeyComp(56) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc181: TSynWebTokenKind;
begin
  if  CssPropKeyComp(23) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc183: TSynWebTokenKind;
begin
  if  CssPropKeyComp(12) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc185: TSynWebTokenKind;
begin
  if  CssPropKeyComp(8) or
      CssPropKeyComp(61) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc187: TSynWebTokenKind;
begin
  if  CssPropKeyComp(54) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc192: TSynWebTokenKind;
begin
  if  CssPropKeyComp(80) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc193: TSynWebTokenKind;
begin
  if  CssPropKeyComp(81) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc197: TSynWebTokenKind;
begin
  if  CssPropKeyComp(3) or
      CssPropKeyComp(71) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc198: TSynWebTokenKind;
begin
  if  CssPropKeyComp(73) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc199: TSynWebTokenKind;
begin
  if  CssPropKeyComp(6) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc201: TSynWebTokenKind;
begin
  if  CssPropKeyComp(36) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc202: TSynWebTokenKind;
begin
  if  CssPropKeyComp(82) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc211: TSynWebTokenKind;
begin
  if  CssPropKeyComp(101) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc215: TSynWebTokenKind;
begin
  if  CssPropKeyComp(72) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc231: TSynWebTokenKind;
begin
  if  CssPropKeyComp(103) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc235: TSynWebTokenKind;
begin
  if  CssPropKeyComp(35) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc239: TSynWebTokenKind;
begin
  if  CssPropKeyComp(2) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc244: TSynWebTokenKind;
begin
  if  CssPropKeyComp(15) or
      CssPropKeyComp(96) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc245: TSynWebTokenKind;
begin
  if  CssPropKeyComp(17) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc251: TSynWebTokenKind;
begin
  if  CssPropKeyComp(5) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc252: TSynWebTokenKind;
begin
  if  CssPropKeyComp(25) or
      CssPropKeyComp(57) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc253: TSynWebTokenKind;
begin
  if  CssPropKeyComp(27) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc262: TSynWebTokenKind;
begin
  if  CssPropKeyComp(16) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc263: TSynWebTokenKind;
begin
  if  CssPropKeyComp(19) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc264: TSynWebTokenKind;
begin
  if  CssPropKeyComp(21) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc270: TSynWebTokenKind;
begin
  if  CssPropKeyComp(26) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc281: TSynWebTokenKind;
begin
  if  CssPropKeyComp(20) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc283: TSynWebTokenKind;
begin
  if  CssPropKeyComp(59) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc286: TSynWebTokenKind;
begin
  if  CssPropKeyComp(9) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc287: TSynWebTokenKind;
begin
  if  CssPropKeyComp(11) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc304: TSynWebTokenKind;
begin
  if  CssPropKeyComp(10) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc334: TSynWebTokenKind;
begin
  if  CssPropKeyComp(58) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;
