function TSynWebEngine.MLSpecialUndef: Boolean;
begin
  Result:=False;
end;

function TSynWebEngine.MLSpecialFunc4: Boolean;
begin
  if  MLSpecialKeyComp(4) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc7: Boolean;
begin
  if  MLSpecialKeyComp(13) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc8: Boolean;
begin
  if  MLSpecialKeyComp(5) or
      MLSpecialKeyComp(342) or
      MLSpecialKeyComp(343) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc10: Boolean;
begin
  if  MLSpecialKeyComp(460) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc12: Boolean;
begin
  if  MLSpecialKeyComp(464) or
      MLSpecialKeyComp(578) or
      MLSpecialKeyComp(579) or
      MLSpecialKeyComp(682) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc14: Boolean;
begin
  if  MLSpecialKeyComp(593) or
      MLSpecialKeyComp(594) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc16: Boolean;
begin
  if  MLSpecialKeyComp(348) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc17: Boolean;
begin
  if  MLSpecialKeyComp(55) or
      MLSpecialKeyComp(469) or
      MLSpecialKeyComp(839) or
      MLSpecialKeyComp(840) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc18: Boolean;
begin
  if  MLSpecialKeyComp(369) or
      MLSpecialKeyComp(696) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc19: Boolean;
begin
  if  MLSpecialKeyComp(27) or
      MLSpecialKeyComp(28) or
      MLSpecialKeyComp(599) or
      MLSpecialKeyComp(904) or
      MLSpecialKeyComp(1061) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc20: Boolean;
begin
  if  MLSpecialKeyComp(203) or
      MLSpecialKeyComp(204) or
      MLSpecialKeyComp(238) or
      MLSpecialKeyComp(239) or
      MLSpecialKeyComp(600) or
      MLSpecialKeyComp(833) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc21: Boolean;
begin
  if  MLSpecialKeyComp(349) or
      MLSpecialKeyComp(595) or
      MLSpecialKeyComp(691) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc22: Boolean;
begin
  if  MLSpecialKeyComp(33) or
      MLSpecialKeyComp(57) or
      MLSpecialKeyComp(58) or
      MLSpecialKeyComp(337) or
      MLSpecialKeyComp(703) or
      MLSpecialKeyComp(1535) or
      MLSpecialKeyComp(1536) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc23: Boolean;
begin
  if  MLSpecialKeyComp(30) or
      MLSpecialKeyComp(714) or
      MLSpecialKeyComp(1087) or
      MLSpecialKeyComp(1439) or
      MLSpecialKeyComp(1721) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc24: Boolean;
begin
  if  MLSpecialKeyComp(568) or
      MLSpecialKeyComp(580) or
      MLSpecialKeyComp(581) or
      MLSpecialKeyComp(601) or
      MLSpecialKeyComp(877) or
      MLSpecialKeyComp(878) or
      MLSpecialKeyComp(905) or
      MLSpecialKeyComp(913) or
      MLSpecialKeyComp(914) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc25: Boolean;
begin
  if  MLSpecialKeyComp(14) or
      MLSpecialKeyComp(15) or
      MLSpecialKeyComp(129) or
      MLSpecialKeyComp(1309) or
      MLSpecialKeyComp(1310) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc26: Boolean;
begin
  if  MLSpecialKeyComp(106) or
      MLSpecialKeyComp(107) or
      MLSpecialKeyComp(484) or
      MLSpecialKeyComp(485) or
      MLSpecialKeyComp(518) or
      MLSpecialKeyComp(519) or
      MLSpecialKeyComp(605) or
      MLSpecialKeyComp(606) or
      MLSpecialKeyComp(1018) or
      MLSpecialKeyComp(1079) or
      MLSpecialKeyComp(1434) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc27: Boolean;
begin
  if  MLSpecialKeyComp(34) or
      MLSpecialKeyComp(232) or
      MLSpecialKeyComp(233) or
      MLSpecialKeyComp(364) or
      MLSpecialKeyComp(625) or
      MLSpecialKeyComp(626) or
      MLSpecialKeyComp(627) or
      MLSpecialKeyComp(642) or
      MLSpecialKeyComp(1541) or
      MLSpecialKeyComp(1542) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc28: Boolean;
begin
  if  MLSpecialKeyComp(102) or
      MLSpecialKeyComp(103) or
      MLSpecialKeyComp(354) or
      MLSpecialKeyComp(355) or
      MLSpecialKeyComp(555) or
      MLSpecialKeyComp(640) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc29: Boolean;
begin
  if  MLSpecialKeyComp(9) or
      MLSpecialKeyComp(10) or
      MLSpecialKeyComp(462) or
      MLSpecialKeyComp(463) or
      MLSpecialKeyComp(473) or
      MLSpecialKeyComp(582) or
      MLSpecialKeyComp(602) or
      MLSpecialKeyComp(650) or
      MLSpecialKeyComp(651) or
      MLSpecialKeyComp(748) or
      MLSpecialKeyComp(799) or
      MLSpecialKeyComp(1033) or
      MLSpecialKeyComp(1327) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc30: Boolean;
begin
  if  MLSpecialKeyComp(25) or
      MLSpecialKeyComp(26) or
      MLSpecialKeyComp(59) or
      MLSpecialKeyComp(92) or
      MLSpecialKeyComp(93) or
      MLSpecialKeyComp(236) or
      MLSpecialKeyComp(240) or
      MLSpecialKeyComp(538) or
      MLSpecialKeyComp(539) or
      MLSpecialKeyComp(999) or
      MLSpecialKeyComp(1000) or
      MLSpecialKeyComp(1041) or
      MLSpecialKeyComp(1445) or
      MLSpecialKeyComp(1446) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc31: Boolean;
begin
  if  MLSpecialKeyComp(356) or
      MLSpecialKeyComp(467) or
      MLSpecialKeyComp(585) or
      MLSpecialKeyComp(591) or
      MLSpecialKeyComp(592) or
      MLSpecialKeyComp(926) or
      MLSpecialKeyComp(927) or
      MLSpecialKeyComp(996) or
      MLSpecialKeyComp(1044) or
      MLSpecialKeyComp(1096) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc32: Boolean;
begin
  if  MLSpecialKeyComp(333) or
      MLSpecialKeyComp(340) or
      MLSpecialKeyComp(341) or
      MLSpecialKeyComp(658) or
      MLSpecialKeyComp(659) or
      MLSpecialKeyComp(979) or
      MLSpecialKeyComp(980) or
      MLSpecialKeyComp(981) or
      MLSpecialKeyComp(1906) or
      MLSpecialKeyComp(1907) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc33: Boolean;
begin
  if  MLSpecialKeyComp(89) or
      MLSpecialKeyComp(226) or
      MLSpecialKeyComp(241) or
      MLSpecialKeyComp(454) or
      MLSpecialKeyComp(455) or
      MLSpecialKeyComp(471) or
      MLSpecialKeyComp(520) or
      MLSpecialKeyComp(521) or
      MLSpecialKeyComp(628) or
      MLSpecialKeyComp(692) or
      MLSpecialKeyComp(693) or
      MLSpecialKeyComp(793) or
      MLSpecialKeyComp(794) or
      MLSpecialKeyComp(813) or
      MLSpecialKeyComp(1258) or
      MLSpecialKeyComp(1259) or
      MLSpecialKeyComp(1304) or
      MLSpecialKeyComp(1305) or
      MLSpecialKeyComp(1955) or
      MLSpecialKeyComp(1956) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc34: Boolean;
begin
  if  MLSpecialKeyComp(6) or
      MLSpecialKeyComp(7) or
      MLSpecialKeyComp(11) or
      MLSpecialKeyComp(12) or
      MLSpecialKeyComp(24) or
      MLSpecialKeyComp(532) or
      MLSpecialKeyComp(533) or
      MLSpecialKeyComp(759) or
      MLSpecialKeyComp(760) or
      MLSpecialKeyComp(795) or
      MLSpecialKeyComp(796) or
      MLSpecialKeyComp(879) or
      MLSpecialKeyComp(1037) or
      MLSpecialKeyComp(1038) or
      MLSpecialKeyComp(1051) or
      MLSpecialKeyComp(1270) or
      MLSpecialKeyComp(1333) or
      MLSpecialKeyComp(1334) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc35: Boolean;
begin
  if  MLSpecialKeyComp(104) or
      MLSpecialKeyComp(254) or
      MLSpecialKeyComp(255) or
      MLSpecialKeyComp(373) or
      MLSpecialKeyComp(450) or
      MLSpecialKeyComp(564) or
      MLSpecialKeyComp(565) or
      MLSpecialKeyComp(574) or
      MLSpecialKeyComp(575) or
      MLSpecialKeyComp(706) or
      MLSpecialKeyComp(777) or
      MLSpecialKeyComp(778) or
      MLSpecialKeyComp(995) or
      MLSpecialKeyComp(1194) or
      MLSpecialKeyComp(1195) or
      MLSpecialKeyComp(1288) or
      MLSpecialKeyComp(1390) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc36: Boolean;
begin
  if  MLSpecialKeyComp(22) or
      MLSpecialKeyComp(23) or
      MLSpecialKeyComp(217) or
      MLSpecialKeyComp(218) or
      MLSpecialKeyComp(219) or
      MLSpecialKeyComp(220) or
      MLSpecialKeyComp(474) or
      MLSpecialKeyComp(882) or
      MLSpecialKeyComp(902) or
      MLSpecialKeyComp(903) or
      MLSpecialKeyComp(1016) or
      MLSpecialKeyComp(1166) or
      MLSpecialKeyComp(1236) or
      MLSpecialKeyComp(1289) or
      MLSpecialKeyComp(1440) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc37: Boolean;
begin
  if  MLSpecialKeyComp(135) or
      MLSpecialKeyComp(586) or
      MLSpecialKeyComp(685) or
      MLSpecialKeyComp(686) or
      MLSpecialKeyComp(1014) or
      MLSpecialKeyComp(1015) or
      MLSpecialKeyComp(1221) or
      MLSpecialKeyComp(1222) or
      MLSpecialKeyComp(1261) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc38: Boolean;
begin
  if  MLSpecialKeyComp(20) or
      MLSpecialKeyComp(21) or
      MLSpecialKeyComp(29) or
      MLSpecialKeyComp(53) or
      MLSpecialKeyComp(54) or
      MLSpecialKeyComp(108) or
      MLSpecialKeyComp(451) or
      MLSpecialKeyComp(452) or
      MLSpecialKeyComp(603) or
      MLSpecialKeyComp(757) or
      MLSpecialKeyComp(758) or
      MLSpecialKeyComp(797) or
      MLSpecialKeyComp(816) or
      MLSpecialKeyComp(830) or
      MLSpecialKeyComp(982) or
      MLSpecialKeyComp(1077) or
      MLSpecialKeyComp(1078) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc39: Boolean;
begin
  if  MLSpecialKeyComp(35) or
      MLSpecialKeyComp(133) or
      MLSpecialKeyComp(134) or
      MLSpecialKeyComp(205) or
      MLSpecialKeyComp(234) or
      MLSpecialKeyComp(235) or
      MLSpecialKeyComp(275) or
      MLSpecialKeyComp(384) or
      MLSpecialKeyComp(385) or
      MLSpecialKeyComp(543) or
      MLSpecialKeyComp(566) or
      MLSpecialKeyComp(567) or
      MLSpecialKeyComp(775) or
      MLSpecialKeyComp(776) or
      MLSpecialKeyComp(906) or
      MLSpecialKeyComp(969) or
      MLSpecialKeyComp(970) or
      MLSpecialKeyComp(1229) or
      MLSpecialKeyComp(1230) or
      MLSpecialKeyComp(1337) or
      MLSpecialKeyComp(1338) or
      MLSpecialKeyComp(1537) or
      MLSpecialKeyComp(1942) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc40: Boolean;
begin
  if  MLSpecialKeyComp(69) or
      MLSpecialKeyComp(128) or
      MLSpecialKeyComp(207) or
      MLSpecialKeyComp(281) or
      MLSpecialKeyComp(282) or
      MLSpecialKeyComp(305) or
      MLSpecialKeyComp(306) or
      MLSpecialKeyComp(476) or
      MLSpecialKeyComp(477) or
      MLSpecialKeyComp(491) or
      MLSpecialKeyComp(536) or
      MLSpecialKeyComp(571) or
      MLSpecialKeyComp(572) or
      MLSpecialKeyComp(573) or
      MLSpecialKeyComp(831) or
      MLSpecialKeyComp(832) or
      MLSpecialKeyComp(1107) or
      MLSpecialKeyComp(1302) or
      MLSpecialKeyComp(1303) or
      MLSpecialKeyComp(1392) or
      MLSpecialKeyComp(1393) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc41: Boolean;
begin
  if  MLSpecialKeyComp(32) or
      MLSpecialKeyComp(66) or
      MLSpecialKeyComp(67) or
      MLSpecialKeyComp(91) or
      MLSpecialKeyComp(330) or
      MLSpecialKeyComp(331) or
      MLSpecialKeyComp(332) or
      MLSpecialKeyComp(382) or
      MLSpecialKeyComp(383) or
      MLSpecialKeyComp(546) or
      MLSpecialKeyComp(652) or
      MLSpecialKeyComp(653) or
      MLSpecialKeyComp(820) or
      MLSpecialKeyComp(829) or
      MLSpecialKeyComp(1007) or
      MLSpecialKeyComp(1008) or
      MLSpecialKeyComp(1082) or
      MLSpecialKeyComp(1245) or
      MLSpecialKeyComp(1246) or
      MLSpecialKeyComp(1249) or
      MLSpecialKeyComp(1373) or
      MLSpecialKeyComp(1374) or
      MLSpecialKeyComp(1458) or
      MLSpecialKeyComp(1459) or
      MLSpecialKeyComp(1548) or
      MLSpecialKeyComp(1586) or
      MLSpecialKeyComp(1762) or
      MLSpecialKeyComp(1943) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc42: Boolean;
begin
  if  MLSpecialKeyComp(19) or
      MLSpecialKeyComp(186) or
      MLSpecialKeyComp(187) or
      MLSpecialKeyComp(214) or
      MLSpecialKeyComp(224) or
      MLSpecialKeyComp(225) or
      MLSpecialKeyComp(229) or
      MLSpecialKeyComp(327) or
      MLSpecialKeyComp(328) or
      MLSpecialKeyComp(350) or
      MLSpecialKeyComp(351) or
      MLSpecialKeyComp(377) or
      MLSpecialKeyComp(378) or
      MLSpecialKeyComp(489) or
      MLSpecialKeyComp(490) or
      MLSpecialKeyComp(534) or
      MLSpecialKeyComp(683) or
      MLSpecialKeyComp(684) or
      MLSpecialKeyComp(688) or
      MLSpecialKeyComp(689) or
      MLSpecialKeyComp(883) or
      MLSpecialKeyComp(1058) or
      MLSpecialKeyComp(1059) or
      MLSpecialKeyComp(1088) or
      MLSpecialKeyComp(1234) or
      MLSpecialKeyComp(1339) or
      MLSpecialKeyComp(1452) or
      MLSpecialKeyComp(1453) or
      MLSpecialKeyComp(1531) or
      MLSpecialKeyComp(1650) or
      MLSpecialKeyComp(1651) or
      MLSpecialKeyComp(1723) or
      MLSpecialKeyComp(1724) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc43: Boolean;
begin
  if  MLSpecialKeyComp(84) or
      MLSpecialKeyComp(130) or
      MLSpecialKeyComp(189) or
      MLSpecialKeyComp(292) or
      MLSpecialKeyComp(293) or
      MLSpecialKeyComp(357) or
      MLSpecialKeyComp(540) or
      MLSpecialKeyComp(547) or
      MLSpecialKeyComp(548) or
      MLSpecialKeyComp(607) or
      MLSpecialKeyComp(711) or
      MLSpecialKeyComp(719) or
      MLSpecialKeyComp(720) or
      MLSpecialKeyComp(755) or
      MLSpecialKeyComp(756) or
      MLSpecialKeyComp(838) or
      MLSpecialKeyComp(907) or
      MLSpecialKeyComp(924) or
      MLSpecialKeyComp(964) or
      MLSpecialKeyComp(1080) or
      MLSpecialKeyComp(1218) or
      MLSpecialKeyComp(1219) or
      MLSpecialKeyComp(1264) or
      MLSpecialKeyComp(1497) or
      MLSpecialKeyComp(1567) or
      MLSpecialKeyComp(1568) or
      MLSpecialKeyComp(1814) or
      MLSpecialKeyComp(1815) or
      MLSpecialKeyComp(1896) or
      MLSpecialKeyComp(1897) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc44: Boolean;
begin
  if  MLSpecialKeyComp(429) or
      MLSpecialKeyComp(430) or
      MLSpecialKeyComp(457) or
      MLSpecialKeyComp(458) or
      MLSpecialKeyComp(459) or
      MLSpecialKeyComp(525) or
      MLSpecialKeyComp(610) or
      MLSpecialKeyComp(611) or
      MLSpecialKeyComp(704) or
      MLSpecialKeyComp(705) or
      MLSpecialKeyComp(773) or
      MLSpecialKeyComp(774) or
      MLSpecialKeyComp(1027) or
      MLSpecialKeyComp(1235) or
      MLSpecialKeyComp(1295) or
      MLSpecialKeyComp(1296) or
      MLSpecialKeyComp(1370) or
      MLSpecialKeyComp(1371) or
      MLSpecialKeyComp(1394) or
      MLSpecialKeyComp(1431) or
      MLSpecialKeyComp(1734) or
      MLSpecialKeyComp(1735) or
      MLSpecialKeyComp(1934) or
      MLSpecialKeyComp(1935) or
      MLSpecialKeyComp(1947) or
      MLSpecialKeyComp(1983) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc45: Boolean;
begin
  if  MLSpecialKeyComp(269) or
      MLSpecialKeyComp(294) or
      MLSpecialKeyComp(345) or
      MLSpecialKeyComp(513) or
      MLSpecialKeyComp(514) or
      MLSpecialKeyComp(597) or
      MLSpecialKeyComp(598) or
      MLSpecialKeyComp(646) or
      MLSpecialKeyComp(647) or
      MLSpecialKeyComp(667) or
      MLSpecialKeyComp(668) or
      MLSpecialKeyComp(736) or
      MLSpecialKeyComp(737) or
      MLSpecialKeyComp(770) or
      MLSpecialKeyComp(771) or
      MLSpecialKeyComp(819) or
      MLSpecialKeyComp(827) or
      MLSpecialKeyComp(828) or
      MLSpecialKeyComp(910) or
      MLSpecialKeyComp(1009) or
      MLSpecialKeyComp(1090) or
      MLSpecialKeyComp(1215) or
      MLSpecialKeyComp(1395) or
      MLSpecialKeyComp(1454) or
      MLSpecialKeyComp(1518) or
      MLSpecialKeyComp(1519) or
      MLSpecialKeyComp(1602) or
      MLSpecialKeyComp(1818) or
      MLSpecialKeyComp(1819) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc46: Boolean;
begin
  if  MLSpecialKeyComp(227) or
      MLSpecialKeyComp(344) or
      MLSpecialKeyComp(368) or
      MLSpecialKeyComp(516) or
      MLSpecialKeyComp(517) or
      MLSpecialKeyComp(544) or
      MLSpecialKeyComp(561) or
      MLSpecialKeyComp(562) or
      MLSpecialKeyComp(576) or
      MLSpecialKeyComp(577) or
      MLSpecialKeyComp(583) or
      MLSpecialKeyComp(596) or
      MLSpecialKeyComp(734) or
      MLSpecialKeyComp(735) or
      MLSpecialKeyComp(997) or
      MLSpecialKeyComp(1060) or
      MLSpecialKeyComp(1089) or
      MLSpecialKeyComp(1104) or
      MLSpecialKeyComp(1432) or
      MLSpecialKeyComp(1433) or
      MLSpecialKeyComp(1444) or
      MLSpecialKeyComp(1562) or
      MLSpecialKeyComp(1588) or
      MLSpecialKeyComp(1608) or
      MLSpecialKeyComp(1671) or
      MLSpecialKeyComp(1832) or
      MLSpecialKeyComp(1920) or
      MLSpecialKeyComp(1921) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc47: Boolean;
begin
  if  MLSpecialKeyComp(74) or
      MLSpecialKeyComp(75) or
      MLSpecialKeyComp(194) or
      MLSpecialKeyComp(211) or
      MLSpecialKeyComp(271) or
      MLSpecialKeyComp(620) or
      MLSpecialKeyComp(621) or
      MLSpecialKeyComp(701) or
      MLSpecialKeyComp(702) or
      MLSpecialKeyComp(712) or
      MLSpecialKeyComp(762) or
      MLSpecialKeyComp(763) or
      MLSpecialKeyComp(780) or
      MLSpecialKeyComp(781) or
      MLSpecialKeyComp(821) or
      MLSpecialKeyComp(958) or
      MLSpecialKeyComp(1028) or
      MLSpecialKeyComp(1054) or
      MLSpecialKeyComp(1055) or
      MLSpecialKeyComp(1220) or
      MLSpecialKeyComp(1242) or
      MLSpecialKeyComp(1312) or
      MLSpecialKeyComp(1421) or
      MLSpecialKeyComp(1430) or
      MLSpecialKeyComp(1552) or
      MLSpecialKeyComp(1553) or
      MLSpecialKeyComp(1561) or
      MLSpecialKeyComp(1653) or
      MLSpecialKeyComp(1654) or
      MLSpecialKeyComp(1938) or
      MLSpecialKeyComp(1939) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc48: Boolean;
begin
  if  MLSpecialKeyComp(56) or
      MLSpecialKeyComp(188) or
      MLSpecialKeyComp(190) or
      MLSpecialKeyComp(191) or
      MLSpecialKeyComp(371) or
      MLSpecialKeyComp(456) or
      MLSpecialKeyComp(622) or
      MLSpecialKeyComp(671) or
      MLSpecialKeyComp(672) or
      MLSpecialKeyComp(687) or
      MLSpecialKeyComp(784) or
      MLSpecialKeyComp(785) or
      MLSpecialKeyComp(822) or
      MLSpecialKeyComp(928) or
      MLSpecialKeyComp(1095) or
      MLSpecialKeyComp(1101) or
      MLSpecialKeyComp(1157) or
      MLSpecialKeyComp(1196) or
      MLSpecialKeyComp(1216) or
      MLSpecialKeyComp(1217) or
      MLSpecialKeyComp(1226) or
      MLSpecialKeyComp(1227) or
      MLSpecialKeyComp(1493) or
      MLSpecialKeyComp(1590) or
      MLSpecialKeyComp(1609) or
      MLSpecialKeyComp(1730) or
      MLSpecialKeyComp(1731) or
      MLSpecialKeyComp(1771) or
      MLSpecialKeyComp(1772) or
      MLSpecialKeyComp(1822) or
      MLSpecialKeyComp(1951) or
      MLSpecialKeyComp(1952) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc49: Boolean;
begin
  if  MLSpecialKeyComp(64) or
      MLSpecialKeyComp(65) or
      MLSpecialKeyComp(147) or
      MLSpecialKeyComp(148) or
      MLSpecialKeyComp(358) or
      MLSpecialKeyComp(494) or
      MLSpecialKeyComp(535) or
      MLSpecialKeyComp(740) or
      MLSpecialKeyComp(741) or
      MLSpecialKeyComp(782) or
      MLSpecialKeyComp(783) or
      MLSpecialKeyComp(802) or
      MLSpecialKeyComp(803) or
      MLSpecialKeyComp(804) or
      MLSpecialKeyComp(931) or
      MLSpecialKeyComp(947) or
      MLSpecialKeyComp(948) or
      MLSpecialKeyComp(1112) or
      MLSpecialKeyComp(1113) or
      MLSpecialKeyComp(1154) or
      MLSpecialKeyComp(1438) or
      MLSpecialKeyComp(1455) or
      MLSpecialKeyComp(1582) or
      MLSpecialKeyComp(1583) or
      MLSpecialKeyComp(1811) or
      MLSpecialKeyComp(1812) or
      MLSpecialKeyComp(1984) or
      MLSpecialKeyComp(1985) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc50: Boolean;
begin
  if  MLSpecialKeyComp(8) or
      MLSpecialKeyComp(119) or
      MLSpecialKeyComp(192) or
      MLSpecialKeyComp(295) or
      MLSpecialKeyComp(329) or
      MLSpecialKeyComp(433) or
      MLSpecialKeyComp(461) or
      MLSpecialKeyComp(551) or
      MLSpecialKeyComp(715) or
      MLSpecialKeyComp(764) or
      MLSpecialKeyComp(765) or
      MLSpecialKeyComp(788) or
      MLSpecialKeyComp(911) or
      MLSpecialKeyComp(912) or
      MLSpecialKeyComp(974) or
      MLSpecialKeyComp(1031) or
      MLSpecialKeyComp(1032) or
      MLSpecialKeyComp(1223) or
      MLSpecialKeyComp(1243) or
      MLSpecialKeyComp(1244) or
      MLSpecialKeyComp(1253) or
      MLSpecialKeyComp(1265) or
      MLSpecialKeyComp(1752) or
      MLSpecialKeyComp(1753) or
      MLSpecialKeyComp(1899) or
      MLSpecialKeyComp(1900) or
      MLSpecialKeyComp(2008) or
      MLSpecialKeyComp(2009) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc51: Boolean;
begin
  if  MLSpecialKeyComp(0) or
      MLSpecialKeyComp(1) or
      MLSpecialKeyComp(60) or
      MLSpecialKeyComp(72) or
      MLSpecialKeyComp(73) or
      MLSpecialKeyComp(95) or
      MLSpecialKeyComp(99) or
      MLSpecialKeyComp(109) or
      MLSpecialKeyComp(131) or
      MLSpecialKeyComp(132) or
      MLSpecialKeyComp(212) or
      MLSpecialKeyComp(302) or
      MLSpecialKeyComp(431) or
      MLSpecialKeyComp(432) or
      MLSpecialKeyComp(437) or
      MLSpecialKeyComp(522) or
      MLSpecialKeyComp(523) or
      MLSpecialKeyComp(710) or
      MLSpecialKeyComp(742) or
      MLSpecialKeyComp(786) or
      MLSpecialKeyComp(787) or
      MLSpecialKeyComp(798) or
      MLSpecialKeyComp(805) or
      MLSpecialKeyComp(817) or
      MLSpecialKeyComp(818) or
      MLSpecialKeyComp(880) or
      MLSpecialKeyComp(1050) or
      MLSpecialKeyComp(1110) or
      MLSpecialKeyComp(1111) or
      MLSpecialKeyComp(1228) or
      MLSpecialKeyComp(1231) or
      MLSpecialKeyComp(1335) or
      MLSpecialKeyComp(1420) or
      MLSpecialKeyComp(1428) or
      MLSpecialKeyComp(1429) or
      MLSpecialKeyComp(1540) or
      MLSpecialKeyComp(1725) or
      MLSpecialKeyComp(1763) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc52: Boolean;
begin
  if  MLSpecialKeyComp(51) or
      MLSpecialKeyComp(52) or
      MLSpecialKeyComp(183) or
      MLSpecialKeyComp(184) or
      MLSpecialKeyComp(196) or
      MLSpecialKeyComp(440) or
      MLSpecialKeyComp(537) or
      MLSpecialKeyComp(716) or
      MLSpecialKeyComp(730) or
      MLSpecialKeyComp(731) or
      MLSpecialKeyComp(761) or
      MLSpecialKeyComp(967) or
      MLSpecialKeyComp(968) or
      MLSpecialKeyComp(1091) or
      MLSpecialKeyComp(1092) or
      MLSpecialKeyComp(1251) or
      MLSpecialKeyComp(1252) or
      MLSpecialKeyComp(1543) or
      MLSpecialKeyComp(1544) or
      MLSpecialKeyComp(1545) or
      MLSpecialKeyComp(1546) or
      MLSpecialKeyComp(1581) or
      MLSpecialKeyComp(1604) or
      MLSpecialKeyComp(1781) or
      MLSpecialKeyComp(1816) or
      MLSpecialKeyComp(2006) or
      MLSpecialKeyComp(2007) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc53: Boolean;
begin
  if  MLSpecialKeyComp(2) or
      MLSpecialKeyComp(3) or
      MLSpecialKeyComp(85) or
      MLSpecialKeyComp(86) or
      MLSpecialKeyComp(87) or
      MLSpecialKeyComp(149) or
      MLSpecialKeyComp(150) or
      MLSpecialKeyComp(151) or
      MLSpecialKeyComp(152) or
      MLSpecialKeyComp(201) or
      MLSpecialKeyComp(202) or
      MLSpecialKeyComp(374) or
      MLSpecialKeyComp(483) or
      MLSpecialKeyComp(612) or
      MLSpecialKeyComp(623) or
      MLSpecialKeyComp(690) or
      MLSpecialKeyComp(792) or
      MLSpecialKeyComp(955) or
      MLSpecialKeyComp(971) or
      MLSpecialKeyComp(1034) or
      MLSpecialKeyComp(1035) or
      MLSpecialKeyComp(1056) or
      MLSpecialKeyComp(1186) or
      MLSpecialKeyComp(1189) or
      MLSpecialKeyComp(1330) or
      MLSpecialKeyComp(1331) or
      MLSpecialKeyComp(1355) or
      MLSpecialKeyComp(1357) or
      MLSpecialKeyComp(1422) or
      MLSpecialKeyComp(1510) or
      MLSpecialKeyComp(1547) or
      MLSpecialKeyComp(1591) or
      MLSpecialKeyComp(1592) or
      MLSpecialKeyComp(1684) or
      MLSpecialKeyComp(1685) or
      MLSpecialKeyComp(1728) or
      MLSpecialKeyComp(1729) or
      MLSpecialKeyComp(1908) or
      MLSpecialKeyComp(1933) or
      MLSpecialKeyComp(1981) or
      MLSpecialKeyComp(1982) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc54: Boolean;
begin
  if  MLSpecialKeyComp(16) or
      MLSpecialKeyComp(17) or
      MLSpecialKeyComp(215) or
      MLSpecialKeyComp(216) or
      MLSpecialKeyComp(334) or
      MLSpecialKeyComp(335) or
      MLSpecialKeyComp(486) or
      MLSpecialKeyComp(700) or
      MLSpecialKeyComp(1057) or
      MLSpecialKeyComp(1168) or
      MLSpecialKeyComp(1169) or
      MLSpecialKeyComp(1224) or
      MLSpecialKeyComp(1376) or
      MLSpecialKeyComp(1377) or
      MLSpecialKeyComp(1423) or
      MLSpecialKeyComp(1615) or
      MLSpecialKeyComp(1740) or
      MLSpecialKeyComp(1741) or
      MLSpecialKeyComp(1809) or
      MLSpecialKeyComp(1810) or
      MLSpecialKeyComp(1825) or
      MLSpecialKeyComp(1901) or
      MLSpecialKeyComp(1902) or
      MLSpecialKeyComp(1903) or
      MLSpecialKeyComp(1904) or
      MLSpecialKeyComp(1909) or
      MLSpecialKeyComp(1959) or
      MLSpecialKeyComp(1977) or
      MLSpecialKeyComp(1978) or
      MLSpecialKeyComp(2000) or
      MLSpecialKeyComp(2001) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc55: Boolean;
begin
  if  MLSpecialKeyComp(242) or
      MLSpecialKeyComp(338) or
      MLSpecialKeyComp(339) or
      MLSpecialKeyComp(372) or
      MLSpecialKeyComp(445) or
      MLSpecialKeyComp(446) or
      MLSpecialKeyComp(498) or
      MLSpecialKeyComp(753) or
      MLSpecialKeyComp(754) or
      MLSpecialKeyComp(814) or
      MLSpecialKeyComp(815) or
      MLSpecialKeyComp(918) or
      MLSpecialKeyComp(1172) or
      MLSpecialKeyComp(1214) or
      MLSpecialKeyComp(1241) or
      MLSpecialKeyComp(1269) or
      MLSpecialKeyComp(1271) or
      MLSpecialKeyComp(1272) or
      MLSpecialKeyComp(1293) or
      MLSpecialKeyComp(1300) or
      MLSpecialKeyComp(1306) or
      MLSpecialKeyComp(1398) or
      MLSpecialKeyComp(1399) or
      MLSpecialKeyComp(1400) or
      MLSpecialKeyComp(1443) or
      MLSpecialKeyComp(1501) or
      MLSpecialKeyComp(1505) or
      MLSpecialKeyComp(1506) or
      MLSpecialKeyComp(1573) or
      MLSpecialKeyComp(1574) or
      MLSpecialKeyComp(1584) or
      MLSpecialKeyComp(1769) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc56: Boolean;
begin
  if  MLSpecialKeyComp(78) or
      MLSpecialKeyComp(96) or
      MLSpecialKeyComp(97) or
      MLSpecialKeyComp(257) or
      MLSpecialKeyComp(322) or
      MLSpecialKeyComp(323) or
      MLSpecialKeyComp(448) or
      MLSpecialKeyComp(449) or
      MLSpecialKeyComp(487) or
      MLSpecialKeyComp(488) or
      MLSpecialKeyComp(503) or
      MLSpecialKeyComp(559) or
      MLSpecialKeyComp(744) or
      MLSpecialKeyComp(1010) or
      MLSpecialKeyComp(1020) or
      MLSpecialKeyComp(1063) or
      MLSpecialKeyComp(1064) or
      MLSpecialKeyComp(1159) or
      MLSpecialKeyComp(1179) or
      MLSpecialKeyComp(1368) or
      MLSpecialKeyComp(1369) or
      MLSpecialKeyComp(1387) or
      MLSpecialKeyComp(1520) or
      MLSpecialKeyComp(1611) or
      MLSpecialKeyComp(1612) or
      MLSpecialKeyComp(1616) or
      MLSpecialKeyComp(1687) or
      MLSpecialKeyComp(1688) or
      MLSpecialKeyComp(1736) or
      MLSpecialKeyComp(1748) or
      MLSpecialKeyComp(1830) or
      MLSpecialKeyComp(1831) or
      MLSpecialKeyComp(1931) or
      MLSpecialKeyComp(1932) or
      MLSpecialKeyComp(1973) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc57: Boolean;
begin
  if  MLSpecialKeyComp(139) or
      MLSpecialKeyComp(140) or
      MLSpecialKeyComp(141) or
      MLSpecialKeyComp(142) or
      MLSpecialKeyComp(197) or
      MLSpecialKeyComp(198) or
      MLSpecialKeyComp(262) or
      MLSpecialKeyComp(438) or
      MLSpecialKeyComp(563) or
      MLSpecialKeyComp(629) or
      MLSpecialKeyComp(962) or
      MLSpecialKeyComp(1062) or
      MLSpecialKeyComp(1086) or
      MLSpecialKeyComp(1239) or
      MLSpecialKeyComp(1313) or
      MLSpecialKeyComp(1379) or
      MLSpecialKeyComp(1380) or
      MLSpecialKeyComp(1396) or
      MLSpecialKeyComp(1402) or
      MLSpecialKeyComp(1417) or
      MLSpecialKeyComp(1418) or
      MLSpecialKeyComp(1419) or
      MLSpecialKeyComp(1496) or
      MLSpecialKeyComp(1605) or
      MLSpecialKeyComp(1627) or
      MLSpecialKeyComp(1766) or
      MLSpecialKeyComp(1767) or
      MLSpecialKeyComp(1948) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc58: Boolean;
begin
  if  MLSpecialKeyComp(36) or
      MLSpecialKeyComp(81) or
      MLSpecialKeyComp(110) or
      MLSpecialKeyComp(289) or
      MLSpecialKeyComp(442) or
      MLSpecialKeyComp(443) or
      MLSpecialKeyComp(465) or
      MLSpecialKeyComp(466) or
      MLSpecialKeyComp(933) or
      MLSpecialKeyComp(972) or
      MLSpecialKeyComp(1006) or
      MLSpecialKeyComp(1017) or
      MLSpecialKeyComp(1237) or
      MLSpecialKeyComp(1283) or
      MLSpecialKeyComp(1308) or
      MLSpecialKeyComp(1404) or
      MLSpecialKeyComp(1500) or
      MLSpecialKeyComp(1516) or
      MLSpecialKeyComp(1517) or
      MLSpecialKeyComp(1554) or
      MLSpecialKeyComp(1593) or
      MLSpecialKeyComp(1603) or
      MLSpecialKeyComp(1644) or
      MLSpecialKeyComp(1645) or
      MLSpecialKeyComp(1801) or
      MLSpecialKeyComp(1802) or
      MLSpecialKeyComp(1803) or
      MLSpecialKeyComp(1841) or
      MLSpecialKeyComp(1842) or
      MLSpecialKeyComp(1979) or
      MLSpecialKeyComp(1980) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc59: Boolean;
begin
  if  MLSpecialKeyComp(94) or
      MLSpecialKeyComp(209) or
      MLSpecialKeyComp(264) or
      MLSpecialKeyComp(265) or
      MLSpecialKeyComp(285) or
      MLSpecialKeyComp(286) or
      MLSpecialKeyComp(296) or
      MLSpecialKeyComp(524) or
      MLSpecialKeyComp(569) or
      MLSpecialKeyComp(570) or
      MLSpecialKeyComp(644) or
      MLSpecialKeyComp(645) or
      MLSpecialKeyComp(680) or
      MLSpecialKeyComp(681) or
      MLSpecialKeyComp(721) or
      MLSpecialKeyComp(749) or
      MLSpecialKeyComp(750) or
      MLSpecialKeyComp(957) or
      MLSpecialKeyComp(989) or
      MLSpecialKeyComp(1083) or
      MLSpecialKeyComp(1084) or
      MLSpecialKeyComp(1085) or
      MLSpecialKeyComp(1175) or
      MLSpecialKeyComp(1639) or
      MLSpecialKeyComp(1640) or
      MLSpecialKeyComp(1732) or
      MLSpecialKeyComp(1889) or
      MLSpecialKeyComp(1890) or
      MLSpecialKeyComp(1923) or
      MLSpecialKeyComp(1924) or
      MLSpecialKeyComp(2017) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc60: Boolean;
begin
  if  MLSpecialKeyComp(37) or
      MLSpecialKeyComp(45) or
      MLSpecialKeyComp(208) or
      MLSpecialKeyComp(308) or
      MLSpecialKeyComp(309) or
      MLSpecialKeyComp(365) or
      MLSpecialKeyComp(366) or
      MLSpecialKeyComp(511) or
      MLSpecialKeyComp(608) or
      MLSpecialKeyComp(624) or
      MLSpecialKeyComp(663) or
      MLSpecialKeyComp(732) or
      MLSpecialKeyComp(733) or
      MLSpecialKeyComp(779) or
      MLSpecialKeyComp(908) or
      MLSpecialKeyComp(973) or
      MLSpecialKeyComp(1173) or
      MLSpecialKeyComp(1182) or
      MLSpecialKeyComp(1262) or
      MLSpecialKeyComp(1375) or
      MLSpecialKeyComp(1555) or
      MLSpecialKeyComp(1594) or
      MLSpecialKeyComp(1788) or
      MLSpecialKeyComp(1789) or
      MLSpecialKeyComp(1823) or
      MLSpecialKeyComp(1940) or
      MLSpecialKeyComp(1941) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc61: Boolean;
begin
  if  MLSpecialKeyComp(38) or
      MLSpecialKeyComp(49) or
      MLSpecialKeyComp(387) or
      MLSpecialKeyComp(698) or
      MLSpecialKeyComp(699) or
      MLSpecialKeyComp(915) or
      MLSpecialKeyComp(963) or
      MLSpecialKeyComp(1180) or
      MLSpecialKeyComp(1275) or
      MLSpecialKeyComp(1281) or
      MLSpecialKeyComp(1282) or
      MLSpecialKeyComp(1351) or
      MLSpecialKeyComp(1352) or
      MLSpecialKeyComp(1413) or
      MLSpecialKeyComp(1414) or
      MLSpecialKeyComp(1558) or
      MLSpecialKeyComp(1559) or
      MLSpecialKeyComp(1657) or
      MLSpecialKeyComp(1658) or
      MLSpecialKeyComp(1686) or
      MLSpecialKeyComp(1694) or
      MLSpecialKeyComp(1695) or
      MLSpecialKeyComp(1871) or
      MLSpecialKeyComp(1872) or
      MLSpecialKeyComp(1936) or
      MLSpecialKeyComp(1962) or
      MLSpecialKeyComp(1963) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc62: Boolean;
begin
  if  MLSpecialKeyComp(39) or
      MLSpecialKeyComp(120) or
      MLSpecialKeyComp(222) or
      MLSpecialKeyComp(298) or
      MLSpecialKeyComp(381) or
      MLSpecialKeyComp(439) or
      MLSpecialKeyComp(512) or
      MLSpecialKeyComp(609) or
      MLSpecialKeyComp(656) or
      MLSpecialKeyComp(669) or
      MLSpecialKeyComp(694) or
      MLSpecialKeyComp(695) or
      MLSpecialKeyComp(738) or
      MLSpecialKeyComp(789) or
      MLSpecialKeyComp(790) or
      MLSpecialKeyComp(946) or
      MLSpecialKeyComp(983) or
      MLSpecialKeyComp(1071) or
      MLSpecialKeyComp(1081) or
      MLSpecialKeyComp(1557) or
      MLSpecialKeyComp(1570) or
      MLSpecialKeyComp(1813) or
      MLSpecialKeyComp(1927) or
      MLSpecialKeyComp(1928) or
      MLSpecialKeyComp(1986) or
      MLSpecialKeyComp(1987) or
      MLSpecialKeyComp(1988) or
      MLSpecialKeyComp(1989) or
      MLSpecialKeyComp(2010) or
      MLSpecialKeyComp(2011) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc63: Boolean;
begin
  if  MLSpecialKeyComp(40) or
      MLSpecialKeyComp(143) or
      MLSpecialKeyComp(144) or
      MLSpecialKeyComp(145) or
      MLSpecialKeyComp(146) or
      MLSpecialKeyComp(168) or
      MLSpecialKeyComp(169) or
      MLSpecialKeyComp(182) or
      MLSpecialKeyComp(185) or
      MLSpecialKeyComp(301) or
      MLSpecialKeyComp(436) or
      MLSpecialKeyComp(500) or
      MLSpecialKeyComp(515) or
      MLSpecialKeyComp(643) or
      MLSpecialKeyComp(657) or
      MLSpecialKeyComp(825) or
      MLSpecialKeyComp(826) or
      MLSpecialKeyComp(1093) or
      MLSpecialKeyComp(1094) or
      MLSpecialKeyComp(1336) or
      MLSpecialKeyComp(1415) or
      MLSpecialKeyComp(1460) or
      MLSpecialKeyComp(1551) or
      MLSpecialKeyComp(1556) or
      MLSpecialKeyComp(1589) or
      MLSpecialKeyComp(1637) or
      MLSpecialKeyComp(1733) or
      MLSpecialKeyComp(1761) or
      MLSpecialKeyComp(1945) or
      MLSpecialKeyComp(1946) or
      MLSpecialKeyComp(2013) or
      MLSpecialKeyComp(2014) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc64: Boolean;
begin
  if  MLSpecialKeyComp(41) or
      MLSpecialKeyComp(266) or
      MLSpecialKeyComp(267) or
      MLSpecialKeyComp(297) or
      MLSpecialKeyComp(453) or
      MLSpecialKeyComp(549) or
      MLSpecialKeyComp(550) or
      MLSpecialKeyComp(932) or
      MLSpecialKeyComp(990) or
      MLSpecialKeyComp(1040) or
      MLSpecialKeyComp(1042) or
      MLSpecialKeyComp(1043) or
      MLSpecialKeyComp(1187) or
      MLSpecialKeyComp(1188) or
      MLSpecialKeyComp(1238) or
      MLSpecialKeyComp(1346) or
      MLSpecialKeyComp(1441) or
      MLSpecialKeyComp(1503) or
      MLSpecialKeyComp(1613) or
      MLSpecialKeyComp(1646) or
      MLSpecialKeyComp(1949) or
      MLSpecialKeyComp(1968) or
      MLSpecialKeyComp(1969) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc65: Boolean;
begin
  if  MLSpecialKeyComp(42) or
      MLSpecialKeyComp(48) or
      MLSpecialKeyComp(88) or
      MLSpecialKeyComp(270) or
      MLSpecialKeyComp(836) or
      MLSpecialKeyComp(929) or
      MLSpecialKeyComp(991) or
      MLSpecialKeyComp(1021) or
      MLSpecialKeyComp(1045) or
      MLSpecialKeyComp(1052) or
      MLSpecialKeyComp(1053) or
      MLSpecialKeyComp(1167) or
      MLSpecialKeyComp(1212) or
      MLSpecialKeyComp(1213) or
      MLSpecialKeyComp(1276) or
      MLSpecialKeyComp(1277) or
      MLSpecialKeyComp(1314) or
      MLSpecialKeyComp(1354) or
      MLSpecialKeyComp(1362) or
      MLSpecialKeyComp(1435) or
      MLSpecialKeyComp(1525) or
      MLSpecialKeyComp(1857) or
      MLSpecialKeyComp(1858) or
      MLSpecialKeyComp(1898) or
      MLSpecialKeyComp(1913) or
      MLSpecialKeyComp(1914) or
      MLSpecialKeyComp(1990) or
      MLSpecialKeyComp(1991) or
      MLSpecialKeyComp(2002) or
      MLSpecialKeyComp(2003) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc66: Boolean;
begin
  if  MLSpecialKeyComp(43) or
      MLSpecialKeyComp(353) or
      MLSpecialKeyComp(379) or
      MLSpecialKeyComp(441) or
      MLSpecialKeyComp(630) or
      MLSpecialKeyComp(801) or
      MLSpecialKeyComp(1005) or
      MLSpecialKeyComp(1019) or
      MLSpecialKeyComp(1108) or
      MLSpecialKeyComp(1267) or
      MLSpecialKeyComp(1292) or
      MLSpecialKeyComp(1456) or
      MLSpecialKeyComp(1571) or
      MLSpecialKeyComp(1572) or
      MLSpecialKeyComp(1757) or
      MLSpecialKeyComp(1824) or
      MLSpecialKeyComp(1887) or
      MLSpecialKeyComp(1905) or
      MLSpecialKeyComp(1911) or
      MLSpecialKeyComp(1912) or
      MLSpecialKeyComp(1960) or
      MLSpecialKeyComp(2015) or
      MLSpecialKeyComp(2016) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc67: Boolean;
begin
  if  MLSpecialKeyComp(44) or
      MLSpecialKeyComp(77) or
      MLSpecialKeyComp(272) or
      MLSpecialKeyComp(590) or
      MLSpecialKeyComp(673) or
      MLSpecialKeyComp(772) or
      MLSpecialKeyComp(887) or
      MLSpecialKeyComp(930) or
      MLSpecialKeyComp(960) or
      MLSpecialKeyComp(1103) or
      MLSpecialKeyComp(1298) or
      MLSpecialKeyComp(1495) or
      MLSpecialKeyComp(1610) or
      MLSpecialKeyComp(1790) or
      MLSpecialKeyComp(1791) or
      MLSpecialKeyComp(1862) or
      MLSpecialKeyComp(1879) or
      MLSpecialKeyComp(1880) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc68: Boolean;
begin
  if  MLSpecialKeyComp(380) or
      MLSpecialKeyComp(447) or
      MLSpecialKeyComp(649) or
      MLSpecialKeyComp(808) or
      MLSpecialKeyComp(985) or
      MLSpecialKeyComp(1030) or
      MLSpecialKeyComp(1176) or
      MLSpecialKeyComp(1199) or
      MLSpecialKeyComp(1200) or
      MLSpecialKeyComp(1201) or
      MLSpecialKeyComp(1202) or
      MLSpecialKeyComp(1232) or
      MLSpecialKeyComp(1233) or
      MLSpecialKeyComp(1316) or
      MLSpecialKeyComp(1388) or
      MLSpecialKeyComp(1389) or
      MLSpecialKeyComp(1504) or
      MLSpecialKeyComp(1566) or
      MLSpecialKeyComp(1597) or
      MLSpecialKeyComp(1678) or
      MLSpecialKeyComp(1758) or
      MLSpecialKeyComp(1785) or
      MLSpecialKeyComp(1876) or
      MLSpecialKeyComp(1974) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc69: Boolean;
begin
  if  MLSpecialKeyComp(68) or
      MLSpecialKeyComp(325) or
      MLSpecialKeyComp(751) or
      MLSpecialKeyComp(752) or
      MLSpecialKeyComp(834) or
      MLSpecialKeyComp(1102) or
      MLSpecialKeyComp(1160) or
      MLSpecialKeyComp(1161) or
      MLSpecialKeyComp(1225) or
      MLSpecialKeyComp(1426) or
      MLSpecialKeyComp(1427) or
      MLSpecialKeyComp(1532) or
      MLSpecialKeyComp(1533) or
      MLSpecialKeyComp(1805) or
      MLSpecialKeyComp(1806) or
      MLSpecialKeyComp(1868) or
      MLSpecialKeyComp(1869) or
      MLSpecialKeyComp(1953) or
      MLSpecialKeyComp(1954) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc70: Boolean;
begin
  if  MLSpecialKeyComp(121) or
      MLSpecialKeyComp(153) or
      MLSpecialKeyComp(154) or
      MLSpecialKeyComp(155) or
      MLSpecialKeyComp(156) or
      MLSpecialKeyComp(468) or
      MLSpecialKeyComp(587) or
      MLSpecialKeyComp(697) or
      MLSpecialKeyComp(708) or
      MLSpecialKeyComp(745) or
      MLSpecialKeyComp(768) or
      MLSpecialKeyComp(769) or
      MLSpecialKeyComp(1183) or
      MLSpecialKeyComp(1256) or
      MLSpecialKeyComp(1260) or
      MLSpecialKeyComp(1266) or
      MLSpecialKeyComp(1318) or
      MLSpecialKeyComp(1332) or
      MLSpecialKeyComp(1502) or
      MLSpecialKeyComp(1526) or
      MLSpecialKeyComp(1538) or
      MLSpecialKeyComp(1539) or
      MLSpecialKeyComp(1760) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc71: Boolean;
begin
  if  MLSpecialKeyComp(170) or
      MLSpecialKeyComp(171) or
      MLSpecialKeyComp(172) or
      MLSpecialKeyComp(173) or
      MLSpecialKeyComp(283) or
      MLSpecialKeyComp(492) or
      MLSpecialKeyComp(497) or
      MLSpecialKeyComp(545) or
      MLSpecialKeyComp(641) or
      MLSpecialKeyComp(654) or
      MLSpecialKeyComp(919) or
      MLSpecialKeyComp(952) or
      MLSpecialKeyComp(984) or
      MLSpecialKeyComp(1307) or
      MLSpecialKeyComp(1527) or
      MLSpecialKeyComp(1565) or
      MLSpecialKeyComp(1585) or
      MLSpecialKeyComp(1722) or
      MLSpecialKeyComp(1726) or
      MLSpecialKeyComp(1727) or
      MLSpecialKeyComp(1799) or
      MLSpecialKeyComp(1800) or
      MLSpecialKeyComp(1874) or
      MLSpecialKeyComp(1875) or
      MLSpecialKeyComp(1994) or
      MLSpecialKeyComp(1995) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc72: Boolean;
begin
  if  MLSpecialKeyComp(111) or
      MLSpecialKeyComp(195) or
      MLSpecialKeyComp(249) or
      MLSpecialKeyComp(427) or
      MLSpecialKeyComp(552) or
      MLSpecialKeyComp(909) or
      MLSpecialKeyComp(1124) or
      MLSpecialKeyComp(1134) or
      MLSpecialKeyComp(1397) or
      MLSpecialKeyComp(1401) or
      MLSpecialKeyComp(1839) or
      MLSpecialKeyComp(1840) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc73: Boolean;
begin
  if  MLSpecialKeyComp(237) or
      MLSpecialKeyComp(250) or
      MLSpecialKeyComp(303) or
      MLSpecialKeyComp(312) or
      MLSpecialKeyComp(493) or
      MLSpecialKeyComp(747) or
      MLSpecialKeyComp(864) or
      MLSpecialKeyComp(920) or
      MLSpecialKeyComp(921) or
      MLSpecialKeyComp(1105) or
      MLSpecialKeyComp(1299) or
      MLSpecialKeyComp(1322) or
      MLSpecialKeyComp(1385) or
      MLSpecialKeyComp(1386) or
      MLSpecialKeyComp(1513) or
      MLSpecialKeyComp(1720) or
      MLSpecialKeyComp(1807) or
      MLSpecialKeyComp(1808) or
      MLSpecialKeyComp(1837) or
      MLSpecialKeyComp(1859) or
      MLSpecialKeyComp(1957) or
      MLSpecialKeyComp(1958) or
      MLSpecialKeyComp(2018) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc74: Boolean;
begin
  if  MLSpecialKeyComp(70) or
      MLSpecialKeyComp(105) or
      MLSpecialKeyComp(137) or
      MLSpecialKeyComp(160) or
      MLSpecialKeyComp(161) or
      MLSpecialKeyComp(162) or
      MLSpecialKeyComp(163) or
      MLSpecialKeyComp(199) or
      MLSpecialKeyComp(200) or
      MLSpecialKeyComp(290) or
      MLSpecialKeyComp(291) or
      MLSpecialKeyComp(336) or
      MLSpecialKeyComp(346) or
      MLSpecialKeyComp(428) or
      MLSpecialKeyComp(470) or
      MLSpecialKeyComp(508) or
      MLSpecialKeyComp(631) or
      MLSpecialKeyComp(807) or
      MLSpecialKeyComp(900) or
      MLSpecialKeyComp(1047) or
      MLSpecialKeyComp(1208) or
      MLSpecialKeyComp(1209) or
      MLSpecialKeyComp(1273) or
      MLSpecialKeyComp(1274) or
      MLSpecialKeyComp(1406) or
      MLSpecialKeyComp(1523) or
      MLSpecialKeyComp(1534) or
      MLSpecialKeyComp(1618) or
      MLSpecialKeyComp(1638) or
      MLSpecialKeyComp(1820) or
      MLSpecialKeyComp(1821) or
      MLSpecialKeyComp(1877) or
      MLSpecialKeyComp(1886) or
      MLSpecialKeyComp(1992) or
      MLSpecialKeyComp(1993) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc75: Boolean;
begin
  if  MLSpecialKeyComp(100) or
      MLSpecialKeyComp(174) or
      MLSpecialKeyComp(175) or
      MLSpecialKeyComp(176) or
      MLSpecialKeyComp(177) or
      MLSpecialKeyComp(278) or
      MLSpecialKeyComp(279) or
      MLSpecialKeyComp(475) or
      MLSpecialKeyComp(504) or
      MLSpecialKeyComp(648) or
      MLSpecialKeyComp(884) or
      MLSpecialKeyComp(998) or
      MLSpecialKeyComp(1184) or
      MLSpecialKeyComp(1207) or
      MLSpecialKeyComp(1211) or
      MLSpecialKeyComp(1342) or
      MLSpecialKeyComp(1366) or
      MLSpecialKeyComp(1436) or
      MLSpecialKeyComp(1703) or
      MLSpecialKeyComp(1704) or
      MLSpecialKeyComp(1750) or
      MLSpecialKeyComp(1751) or
      MLSpecialKeyComp(1792) or
      MLSpecialKeyComp(1793) or
      MLSpecialKeyComp(1944) or
      MLSpecialKeyComp(1950) or
      MLSpecialKeyComp(1975) or
      MLSpecialKeyComp(1976) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc76: Boolean;
begin
  if  MLSpecialKeyComp(83) or
      MLSpecialKeyComp(115) or
      MLSpecialKeyComp(560) or
      MLSpecialKeyComp(679) or
      MLSpecialKeyComp(806) or
      MLSpecialKeyComp(1022) or
      MLSpecialKeyComp(1291) or
      MLSpecialKeyComp(1297) or
      MLSpecialKeyComp(1315) or
      MLSpecialKeyComp(1600) or
      MLSpecialKeyComp(1617) or
      MLSpecialKeyComp(1743) or
      MLSpecialKeyComp(1910) or
      MLSpecialKeyComp(1929) or
      MLSpecialKeyComp(1937) or
      MLSpecialKeyComp(1996) or
      MLSpecialKeyComp(1997) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc77: Boolean;
begin
  if  MLSpecialKeyComp(299) or
      MLSpecialKeyComp(526) or
      MLSpecialKeyComp(718) or
      MLSpecialKeyComp(809) or
      MLSpecialKeyComp(810) or
      MLSpecialKeyComp(965) or
      MLSpecialKeyComp(1158) or
      MLSpecialKeyComp(1174) or
      MLSpecialKeyComp(1290) or
      MLSpecialKeyComp(1549) or
      MLSpecialKeyComp(1642) or
      MLSpecialKeyComp(1998) or
      MLSpecialKeyComp(1999) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc78: Boolean;
begin
  if  MLSpecialKeyComp(80) or
      MLSpecialKeyComp(221) or
      MLSpecialKeyComp(276) or
      MLSpecialKeyComp(386) or
      MLSpecialKeyComp(823) or
      MLSpecialKeyComp(901) or
      MLSpecialKeyComp(986) or
      MLSpecialKeyComp(1023) or
      MLSpecialKeyComp(1106) or
      MLSpecialKeyComp(1378) or
      MLSpecialKeyComp(1412) or
      MLSpecialKeyComp(1457) or
      MLSpecialKeyComp(1619) or
      MLSpecialKeyComp(1961) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc79: Boolean;
begin
  if  MLSpecialKeyComp(258) or
      MLSpecialKeyComp(311) or
      MLSpecialKeyComp(313) or
      MLSpecialKeyComp(319) or
      MLSpecialKeyComp(478) or
      MLSpecialKeyComp(959) or
      MLSpecialKeyComp(1164) or
      MLSpecialKeyComp(1674) or
      MLSpecialKeyComp(1716) or
      MLSpecialKeyComp(1717) or
      MLSpecialKeyComp(1878) or
      MLSpecialKeyComp(1966) or
      MLSpecialKeyComp(1967) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc80: Boolean;
begin
  if  MLSpecialKeyComp(82) or
      MLSpecialKeyComp(164) or
      MLSpecialKeyComp(165) or
      MLSpecialKeyComp(166) or
      MLSpecialKeyComp(167) or
      MLSpecialKeyComp(206) or
      MLSpecialKeyComp(307) or
      MLSpecialKeyComp(310) or
      MLSpecialKeyComp(678) or
      MLSpecialKeyComp(766) or
      MLSpecialKeyComp(767) or
      MLSpecialKeyComp(1024) or
      MLSpecialKeyComp(1353) or
      MLSpecialKeyComp(1405) or
      MLSpecialKeyComp(1450) or
      MLSpecialKeyComp(1511) or
      MLSpecialKeyComp(1587) or
      MLSpecialKeyComp(1715) or
      MLSpecialKeyComp(1749) or
      MLSpecialKeyComp(1829) or
      MLSpecialKeyComp(1873) or
      MLSpecialKeyComp(2004) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc81: Boolean;
begin
  if  MLSpecialKeyComp(18) or
      MLSpecialKeyComp(178) or
      MLSpecialKeyComp(179) or
      MLSpecialKeyComp(180) or
      MLSpecialKeyComp(181) or
      MLSpecialKeyComp(268) or
      MLSpecialKeyComp(499) or
      MLSpecialKeyComp(812) or
      MLSpecialKeyComp(987) or
      MLSpecialKeyComp(1203) or
      MLSpecialKeyComp(1263) or
      MLSpecialKeyComp(1278) or
      MLSpecialKeyComp(1279) or
      MLSpecialKeyComp(1284) or
      MLSpecialKeyComp(1294) or
      MLSpecialKeyComp(1628) or
      MLSpecialKeyComp(1629) or
      MLSpecialKeyComp(1652) or
      MLSpecialKeyComp(1765) or
      MLSpecialKeyComp(1770) or
      MLSpecialKeyComp(1922) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc82: Boolean;
begin
  if  MLSpecialKeyComp(138) or
      MLSpecialKeyComp(509) or
      MLSpecialKeyComp(634) or
      MLSpecialKeyComp(724) or
      MLSpecialKeyComp(1074) or
      MLSpecialKeyComp(1383) or
      MLSpecialKeyComp(1403) or
      MLSpecialKeyComp(1636) or
      MLSpecialKeyComp(1882) or
      MLSpecialKeyComp(1891) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc83: Boolean;
begin
  if  MLSpecialKeyComp(300) or
      MLSpecialKeyComp(713) or
      MLSpecialKeyComp(1198) or
      MLSpecialKeyComp(1257) or
      MLSpecialKeyComp(1350) or
      MLSpecialKeyComp(1407) or
      MLSpecialKeyComp(1408) or
      MLSpecialKeyComp(1620) or
      MLSpecialKeyComp(1643) or
      MLSpecialKeyComp(1668) or
      MLSpecialKeyComp(1817) or
      MLSpecialKeyComp(1826) or
      MLSpecialKeyComp(1833) or
      MLSpecialKeyComp(1881) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc84: Boolean;
begin
  if  MLSpecialKeyComp(46) or
      MLSpecialKeyComp(90) or
      MLSpecialKeyComp(347) or
      MLSpecialKeyComp(635) or
      MLSpecialKeyComp(664) or
      MLSpecialKeyComp(956) or
      MLSpecialKeyComp(975) or
      MLSpecialKeyComp(1001) or
      MLSpecialKeyComp(1165) or
      MLSpecialKeyComp(1424) or
      MLSpecialKeyComp(1451) or
      MLSpecialKeyComp(1524) or
      MLSpecialKeyComp(1669) or
      MLSpecialKeyComp(1689) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc85: Boolean;
begin
  if  MLSpecialKeyComp(50) or
      MLSpecialKeyComp(136) or
      MLSpecialKeyComp(556) or
      MLSpecialKeyComp(588) or
      MLSpecialKeyComp(709) or
      MLSpecialKeyComp(966) or
      MLSpecialKeyComp(992) or
      MLSpecialKeyComp(1205) or
      MLSpecialKeyComp(1563) or
      MLSpecialKeyComp(1690) or
      MLSpecialKeyComp(1828) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc86: Boolean;
begin
  if  MLSpecialKeyComp(31) or
      MLSpecialKeyComp(247) or
      MLSpecialKeyComp(424) or
      MLSpecialKeyComp(639) or
      MLSpecialKeyComp(717) or
      MLSpecialKeyComp(723) or
      MLSpecialKeyComp(1197) or
      MLSpecialKeyComp(1655) or
      MLSpecialKeyComp(1661) or
      MLSpecialKeyComp(1662) or
      MLSpecialKeyComp(1691) or
      MLSpecialKeyComp(1746) or
      MLSpecialKeyComp(1773) or
      MLSpecialKeyComp(1780) or
      MLSpecialKeyComp(1870) or
      MLSpecialKeyComp(1884) or
      MLSpecialKeyComp(1965) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc87: Boolean;
begin
  if  MLSpecialKeyComp(246) or
      MLSpecialKeyComp(434) or
      MLSpecialKeyComp(435) or
      MLSpecialKeyComp(506) or
      MLSpecialKeyComp(557) or
      MLSpecialKeyComp(835) or
      MLSpecialKeyComp(1048) or
      MLSpecialKeyComp(1247) or
      MLSpecialKeyComp(1248) or
      MLSpecialKeyComp(1320) or
      MLSpecialKeyComp(1359) or
      MLSpecialKeyComp(1410) or
      MLSpecialKeyComp(1411) or
      MLSpecialKeyComp(1682) or
      MLSpecialKeyComp(1737) or
      MLSpecialKeyComp(1759) or
      MLSpecialKeyComp(1925) or
      MLSpecialKeyComp(1926) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc88: Boolean;
begin
  if  MLSpecialKeyComp(47) or
      MLSpecialKeyComp(326) or
      MLSpecialKeyComp(376) or
      MLSpecialKeyComp(1070) or
      MLSpecialKeyComp(1204) or
      MLSpecialKeyComp(1606) or
      MLSpecialKeyComp(1607) or
      MLSpecialKeyComp(1764) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc89: Boolean;
begin
  if  MLSpecialKeyComp(248) or
      MLSpecialKeyComp(304) or
      MLSpecialKeyComp(558) or
      MLSpecialKeyComp(1285) or
      MLSpecialKeyComp(1301) or
      MLSpecialKeyComp(1356) or
      MLSpecialKeyComp(1372) or
      MLSpecialKeyComp(1854) or
      MLSpecialKeyComp(1865) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc90: Boolean;
begin
  if  MLSpecialKeyComp(62) or
      MLSpecialKeyComp(213) or
      MLSpecialKeyComp(495) or
      MLSpecialKeyComp(496) or
      MLSpecialKeyComp(743) or
      MLSpecialKeyComp(811) or
      MLSpecialKeyComp(885) or
      MLSpecialKeyComp(951) or
      MLSpecialKeyComp(1367) or
      MLSpecialKeyComp(1521) or
      MLSpecialKeyComp(1641) or
      MLSpecialKeyComp(1649) or
      MLSpecialKeyComp(1892) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc91: Boolean;
begin
  if  MLSpecialKeyComp(674) or
      MLSpecialKeyComp(675) or
      MLSpecialKeyComp(739) or
      MLSpecialKeyComp(1075) or
      MLSpecialKeyComp(1155) or
      MLSpecialKeyComp(1206) or
      MLSpecialKeyComp(1250) or
      MLSpecialKeyComp(1442) or
      MLSpecialKeyComp(1515) or
      MLSpecialKeyComp(1834) or
      MLSpecialKeyComp(1867) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc92: Boolean;
begin
  if  MLSpecialKeyComp(314) or
      MLSpecialKeyComp(426) or
      MLSpecialKeyComp(746) or
      MLSpecialKeyComp(1480) or
      MLSpecialKeyComp(1623) or
      MLSpecialKeyComp(1745) or
      MLSpecialKeyComp(1972) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc93: Boolean;
begin
  if  MLSpecialKeyComp(256) or
      MLSpecialKeyComp(726) or
      MLSpecialKeyComp(950) or
      MLSpecialKeyComp(1321) or
      MLSpecialKeyComp(1437) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc94: Boolean;
begin
  if  MLSpecialKeyComp(114) or
      MLSpecialKeyComp(223) or
      MLSpecialKeyComp(245) or
      MLSpecialKeyComp(800) or
      MLSpecialKeyComp(889) or
      MLSpecialKeyComp(1065) or
      MLSpecialKeyComp(1786) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc95: Boolean;
begin
  if  MLSpecialKeyComp(389) or
      MLSpecialKeyComp(584) or
      MLSpecialKeyComp(824) or
      MLSpecialKeyComp(949) or
      MLSpecialKeyComp(977) or
      MLSpecialKeyComp(978) or
      MLSpecialKeyComp(1029) or
      MLSpecialKeyComp(1125) or
      MLSpecialKeyComp(1135) or
      MLSpecialKeyComp(1324) or
      MLSpecialKeyComp(1348) or
      MLSpecialKeyComp(1360) or
      MLSpecialKeyComp(1569) or
      MLSpecialKeyComp(1692) or
      MLSpecialKeyComp(1747) or
      MLSpecialKeyComp(1893) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc96: Boolean;
begin
  if  MLSpecialKeyComp(71) or
      MLSpecialKeyComp(287) or
      MLSpecialKeyComp(527) or
      MLSpecialKeyComp(727) or
      MLSpecialKeyComp(897) or
      MLSpecialKeyComp(1126) or
      MLSpecialKeyComp(1136) or
      MLSpecialKeyComp(1409) or
      MLSpecialKeyComp(1596) or
      MLSpecialKeyComp(1796) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc97: Boolean;
begin
  if  MLSpecialKeyComp(589) or
      MLSpecialKeyComp(722) or
      MLSpecialKeyComp(916) or
      MLSpecialKeyComp(1127) or
      MLSpecialKeyComp(1137) or
      MLSpecialKeyComp(1177) or
      MLSpecialKeyComp(1349) or
      MLSpecialKeyComp(1358) or
      MLSpecialKeyComp(1624) or
      MLSpecialKeyComp(1660) or
      MLSpecialKeyComp(1712) or
      MLSpecialKeyComp(2012) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc98: Boolean;
begin
  if  MLSpecialKeyComp(193) or
      MLSpecialKeyComp(395) or
      MLSpecialKeyComp(1319) or
      MLSpecialKeyComp(1670) or
      MLSpecialKeyComp(1713) or
      MLSpecialKeyComp(1719) or
      MLSpecialKeyComp(1930) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc99: Boolean;
begin
  if  MLSpecialKeyComp(76) or
      MLSpecialKeyComp(113) or
      MLSpecialKeyComp(994) or
      MLSpecialKeyComp(1149) or
      MLSpecialKeyComp(1317) or
      MLSpecialKeyComp(1508) or
      MLSpecialKeyComp(1530) or
      MLSpecialKeyComp(1560) or
      MLSpecialKeyComp(1680) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc100: Boolean;
begin
  if  MLSpecialKeyComp(388) or
      MLSpecialKeyComp(638) or
      MLSpecialKeyComp(661) or
      MLSpecialKeyComp(881) or
      MLSpecialKeyComp(895) or
      MLSpecialKeyComp(922) or
      MLSpecialKeyComp(1156) or
      MLSpecialKeyComp(1268) or
      MLSpecialKeyComp(1365) or
      MLSpecialKeyComp(1683) or
      MLSpecialKeyComp(1696) or
      MLSpecialKeyComp(1706) or
      MLSpecialKeyComp(1707) or
      MLSpecialKeyComp(1738) or
      MLSpecialKeyComp(1739) or
      MLSpecialKeyComp(1756) or
      MLSpecialKeyComp(1970) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc101: Boolean;
begin
  if  MLSpecialKeyComp(112) or
      MLSpecialKeyComp(324) or
      MLSpecialKeyComp(444) or
      MLSpecialKeyComp(481) or
      MLSpecialKeyComp(837) or
      MLSpecialKeyComp(993) or
      MLSpecialKeyComp(1025) or
      MLSpecialKeyComp(1240) or
      MLSpecialKeyComp(1280) or
      MLSpecialKeyComp(1425) or
      MLSpecialKeyComp(1507) or
      MLSpecialKeyComp(1681) or
      MLSpecialKeyComp(1768) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc102: Boolean;
begin
  if  MLSpecialKeyComp(472) or
      MLSpecialKeyComp(848) or
      MLSpecialKeyComp(976) or
      MLSpecialKeyComp(1036) or
      MLSpecialKeyComp(1382) or
      MLSpecialKeyComp(1693) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc103: Boolean;
begin
  if  MLSpecialKeyComp(98) or
      MLSpecialKeyComp(961) or
      MLSpecialKeyComp(1601) or
      MLSpecialKeyComp(1777) or
      MLSpecialKeyComp(1794) or
      MLSpecialKeyComp(1795) or
      MLSpecialKeyComp(1804) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc104: Boolean;
begin
  if  MLSpecialKeyComp(228) or
      MLSpecialKeyComp(230) or
      MLSpecialKeyComp(231) or
      MLSpecialKeyComp(554) or
      MLSpecialKeyComp(1046) or
      MLSpecialKeyComp(1130) or
      MLSpecialKeyComp(1384) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc105: Boolean;
begin
  if  MLSpecialKeyComp(352) or
      MLSpecialKeyComp(899) or
      MLSpecialKeyComp(1039) or
      MLSpecialKeyComp(1118) or
      MLSpecialKeyComp(1701) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc106: Boolean;
begin
  if  MLSpecialKeyComp(505) or
      MLSpecialKeyComp(707) or
      MLSpecialKeyComp(1049) or
      MLSpecialKeyComp(1311) or
      MLSpecialKeyComp(1498) or
      MLSpecialKeyComp(1577) or
      MLSpecialKeyComp(1700) or
      MLSpecialKeyComp(1754) or
      MLSpecialKeyComp(1827) or
      MLSpecialKeyComp(1860) or
      MLSpecialKeyComp(1861) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc107: Boolean;
begin
  if  MLSpecialKeyComp(79) or
      MLSpecialKeyComp(118) or
      MLSpecialKeyComp(159) or
      MLSpecialKeyComp(263) or
      MLSpecialKeyComp(391) or
      MLSpecialKeyComp(1598) or
      MLSpecialKeyComp(1964) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc108: Boolean;
begin
  if  MLSpecialKeyComp(413) or
      MLSpecialKeyComp(886) or
      MLSpecialKeyComp(1522) or
      MLSpecialKeyComp(1550) or
      MLSpecialKeyComp(1656) or
      MLSpecialKeyComp(1663) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc109: Boolean;
begin
  if  MLSpecialKeyComp(158) or
      MLSpecialKeyComp(632) or
      MLSpecialKeyComp(853) or
      MLSpecialKeyComp(1012) or
      MLSpecialKeyComp(1013) or
      MLSpecialKeyComp(1115) or
      MLSpecialKeyComp(1325) or
      MLSpecialKeyComp(1416) or
      MLSpecialKeyComp(1595) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc110: Boolean;
begin
  if  MLSpecialKeyComp(123) or
      MLSpecialKeyComp(510) or
      MLSpecialKeyComp(896) or
      MLSpecialKeyComp(1076) or
      MLSpecialKeyComp(1659) or
      MLSpecialKeyComp(1699) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc111: Boolean;
begin
  if  MLSpecialKeyComp(317) or
      MLSpecialKeyComp(604) or
      MLSpecialKeyComp(1178) or
      MLSpecialKeyComp(1742) or
      MLSpecialKeyComp(1915) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc112: Boolean;
begin
  if  MLSpecialKeyComp(63) or
      MLSpecialKeyComp(274) or
      MLSpecialKeyComp(1210) or
      MLSpecialKeyComp(1529) or
      MLSpecialKeyComp(1714) or
      MLSpecialKeyComp(1843) or
      MLSpecialKeyComp(1844) or
      MLSpecialKeyComp(1845) or
      MLSpecialKeyComp(1866) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc113: Boolean;
begin
  if  MLSpecialKeyComp(122) or
      MLSpecialKeyComp(370) or
      MLSpecialKeyComp(1971) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc114: Boolean;
begin
  if  MLSpecialKeyComp(677) or
      MLSpecialKeyComp(791) or
      MLSpecialKeyComp(988) or
      MLSpecialKeyComp(1614) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc115: Boolean;
begin
  if  MLSpecialKeyComp(124) or
      MLSpecialKeyComp(284) or
      MLSpecialKeyComp(390) or
      MLSpecialKeyComp(1784) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc116: Boolean;
begin
  if  MLSpecialKeyComp(253) or
      MLSpecialKeyComp(273) or
      MLSpecialKeyComp(925) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc117: Boolean;
begin
  if  MLSpecialKeyComp(157) or
      MLSpecialKeyComp(277) or
      MLSpecialKeyComp(923) or
      MLSpecialKeyComp(1329) or
      MLSpecialKeyComp(1718) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc118: Boolean;
begin
  if  MLSpecialKeyComp(252) or
      MLSpecialKeyComp(660) or
      MLSpecialKeyComp(662) or
      MLSpecialKeyComp(842) or
      MLSpecialKeyComp(843) or
      MLSpecialKeyComp(844) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc119: Boolean;
begin
  if  MLSpecialKeyComp(1361) or
      MLSpecialKeyComp(1783) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc120: Boolean;
begin
  if  MLSpecialKeyComp(392) or
      MLSpecialKeyComp(1170) or
      MLSpecialKeyComp(1286) or
      MLSpecialKeyComp(1391) or
      MLSpecialKeyComp(1512) or
      MLSpecialKeyComp(1564) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc121: Boolean;
begin
  if  MLSpecialKeyComp(655) or
      MLSpecialKeyComp(1004) or
      MLSpecialKeyComp(1468) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc122: Boolean;
begin
  if  MLSpecialKeyComp(636) or
      MLSpecialKeyComp(890) or
      MLSpecialKeyComp(1181) or
      MLSpecialKeyComp(1621) or
      MLSpecialKeyComp(1666) or
      MLSpecialKeyComp(1702) or
      MLSpecialKeyComp(1708) or
      MLSpecialKeyComp(1835) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc123: Boolean;
begin
  if  MLSpecialKeyComp(318) or
      MLSpecialKeyComp(479) or
      MLSpecialKeyComp(1117) or
      MLSpecialKeyComp(1120) or
      MLSpecialKeyComp(1499) or
      MLSpecialKeyComp(1697) or
      MLSpecialKeyComp(1782) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc124: Boolean;
begin
  if  MLSpecialKeyComp(393) or
      MLSpecialKeyComp(619) or
      MLSpecialKeyComp(1138) or
      MLSpecialKeyComp(1528) or
      MLSpecialKeyComp(1705) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc125: Boolean;
begin
  if  MLSpecialKeyComp(1011) or
      MLSpecialKeyComp(1345) or
      MLSpecialKeyComp(1664) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc126: Boolean;
begin
  if  MLSpecialKeyComp(251) or
      MLSpecialKeyComp(875) or
      MLSpecialKeyComp(1326) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc127: Boolean;
begin
  if  MLSpecialKeyComp(101) or
      MLSpecialKeyComp(1003) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc128: Boolean;
begin
  if  MLSpecialKeyComp(360) or
      MLSpecialKeyComp(1146) or
      MLSpecialKeyComp(1473) or
      MLSpecialKeyComp(1787) or
      MLSpecialKeyComp(1885) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc129: Boolean;
begin
  if  MLSpecialKeyComp(367) or
      MLSpecialKeyComp(617) or
      MLSpecialKeyComp(868) or
      MLSpecialKeyComp(894) or
      MLSpecialKeyComp(1328) or
      MLSpecialKeyComp(1677) or
      MLSpecialKeyComp(1775) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc130: Boolean;
begin
  if  MLSpecialKeyComp(613) or
      MLSpecialKeyComp(917) or
      MLSpecialKeyComp(1916) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc131: Boolean;
begin
  if  MLSpecialKeyComp(408) or
      MLSpecialKeyComp(409) or
      MLSpecialKeyComp(410) or
      MLSpecialKeyComp(1343) or
      MLSpecialKeyComp(1883) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc132: Boolean;
begin
  if  MLSpecialKeyComp(399) or
      MLSpecialKeyComp(528) or
      MLSpecialKeyComp(940) or
      MLSpecialKeyComp(1097) or
      MLSpecialKeyComp(1098) or
      MLSpecialKeyComp(1340) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc133: Boolean;
begin
  if  MLSpecialKeyComp(501) or
      MLSpecialKeyComp(1846) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc135: Boolean;
begin
  if  MLSpecialKeyComp(633) or
      MLSpecialKeyComp(1648) or
      MLSpecialKeyComp(1675) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc136: Boolean;
begin
  if  MLSpecialKeyComp(507) or
      MLSpecialKeyComp(553) or
      MLSpecialKeyComp(1185) or
      MLSpecialKeyComp(1625) or
      MLSpecialKeyComp(1672) or
      MLSpecialKeyComp(1710) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc137: Boolean;
begin
  if  MLSpecialKeyComp(1462) or
      MLSpecialKeyComp(1463) or
      MLSpecialKeyComp(1464) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc139: Boolean;
begin
  if  MLSpecialKeyComp(359) or
      MLSpecialKeyComp(363) or
      MLSpecialKeyComp(637) or
      MLSpecialKeyComp(845) or
      MLSpecialKeyComp(891) or
      MLSpecialKeyComp(1667) or
      MLSpecialKeyComp(1709) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc140: Boolean;
begin
  if  MLSpecialKeyComp(529) or
      MLSpecialKeyComp(530) or
      MLSpecialKeyComp(1002) or
      MLSpecialKeyComp(1918) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc141: Boolean;
begin
  if  MLSpecialKeyComp(117) or
      MLSpecialKeyComp(531) or
      MLSpecialKeyComp(1744) or
      MLSpecialKeyComp(1838) or
      MLSpecialKeyComp(1888) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc142: Boolean;
begin
  if  MLSpecialKeyComp(362) or
      MLSpecialKeyComp(841) or
      MLSpecialKeyComp(1665) or
      MLSpecialKeyComp(1774) or
      MLSpecialKeyComp(1863) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc143: Boolean;
begin
  if  MLSpecialKeyComp(315) or
      MLSpecialKeyComp(502) or
      MLSpecialKeyComp(1190) or
      MLSpecialKeyComp(1341) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc144: Boolean;
begin
  if  MLSpecialKeyComp(1026) or
      MLSpecialKeyComp(1323) or
      MLSpecialKeyComp(1622) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc145: Boolean;
begin
  if  MLSpecialKeyComp(888) or
      MLSpecialKeyComp(1119) or
      MLSpecialKeyComp(1491) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc146: Boolean;
begin
  if  MLSpecialKeyComp(728) or
      MLSpecialKeyComp(1347) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc147: Boolean;
begin
  if  MLSpecialKeyComp(316) or
      MLSpecialKeyComp(876) or
      MLSpecialKeyComp(1673) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc148: Boolean;
begin
  if  MLSpecialKeyComp(375) or
      MLSpecialKeyComp(616) or
      MLSpecialKeyComp(865) or
      MLSpecialKeyComp(1484) or
      MLSpecialKeyComp(1778) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc149: Boolean;
begin
  if  MLSpecialKeyComp(1152) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc150: Boolean;
begin
  if  MLSpecialKeyComp(869) or
      MLSpecialKeyComp(1679) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc151: Boolean;
begin
  if  MLSpecialKeyComp(404) or
      MLSpecialKeyComp(725) or
      MLSpecialKeyComp(1162) or
      MLSpecialKeyComp(1163) or
      MLSpecialKeyComp(1776) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc152: Boolean;
begin
  if  MLSpecialKeyComp(411) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc153: Boolean;
begin
  if  MLSpecialKeyComp(1381) or
      MLSpecialKeyComp(1711) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc154: Boolean;
begin
  if  MLSpecialKeyComp(1109) or
      MLSpecialKeyComp(1133) or
      MLSpecialKeyComp(1635) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc155: Boolean;
begin
  if  MLSpecialKeyComp(1150) or
      MLSpecialKeyComp(1509) or
      MLSpecialKeyComp(1514) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc156: Boolean;
begin
  if  MLSpecialKeyComp(866) or
      MLSpecialKeyComp(1363) or
      MLSpecialKeyComp(1494) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc157: Boolean;
begin
  if  MLSpecialKeyComp(1578) or
      MLSpecialKeyComp(1755) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc158: Boolean;
begin
  if  MLSpecialKeyComp(126) or
      MLSpecialKeyComp(1465) or
      MLSpecialKeyComp(1626) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc160: Boolean;
begin
  if  MLSpecialKeyComp(116) or
      MLSpecialKeyComp(847) or
      MLSpecialKeyComp(1131) or
      MLSpecialKeyComp(1153) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc161: Boolean;
begin
  if  MLSpecialKeyComp(425) or
      MLSpecialKeyComp(1461) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc162: Boolean;
begin
  if  MLSpecialKeyComp(849) or
      MLSpecialKeyComp(893) or
      MLSpecialKeyComp(1192) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc163: Boolean;
begin
  if  MLSpecialKeyComp(873) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc165: Boolean;
begin
  if  MLSpecialKeyComp(867) or
      MLSpecialKeyComp(1191) or
      MLSpecialKeyComp(1919) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc166: Boolean;
begin
  if  MLSpecialKeyComp(934) or
      MLSpecialKeyComp(935) or
      MLSpecialKeyComp(936) or
      MLSpecialKeyComp(1114) or
      MLSpecialKeyComp(1447) or
      MLSpecialKeyComp(1492) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc167: Boolean;
begin
  if  MLSpecialKeyComp(665) or
      MLSpecialKeyComp(729) or
      MLSpecialKeyComp(855) or
      MLSpecialKeyComp(1481) or
      MLSpecialKeyComp(1631) or
      MLSpecialKeyComp(1852) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc168: Boolean;
begin
  if  MLSpecialKeyComp(243) or
      MLSpecialKeyComp(1848) or
      MLSpecialKeyComp(1849) or
      MLSpecialKeyComp(1850) or
      MLSpecialKeyComp(1864) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc169: Boolean;
begin
  if  MLSpecialKeyComp(1364) or
      MLSpecialKeyComp(1485) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc170: Boolean;
begin
  if  MLSpecialKeyComp(407) or
      MLSpecialKeyComp(1779) or
      MLSpecialKeyComp(1894) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc171: Boolean;
begin
  if  MLSpecialKeyComp(125) or
      MLSpecialKeyComp(405) or
      MLSpecialKeyComp(1171) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc172: Boolean;
begin
  if  MLSpecialKeyComp(61) or
      MLSpecialKeyComp(676) or
      MLSpecialKeyComp(2005) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc173: Boolean;
begin
  if  MLSpecialKeyComp(1123) or
      MLSpecialKeyComp(1851) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc175: Boolean;
begin
  if  MLSpecialKeyComp(210) or
      MLSpecialKeyComp(1482) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc176: Boolean;
begin
  if  MLSpecialKeyComp(944) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc177: Boolean;
begin
  if  MLSpecialKeyComp(127) or
      MLSpecialKeyComp(397) or
      MLSpecialKeyComp(898) or
      MLSpecialKeyComp(1073) or
      MLSpecialKeyComp(1599) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc178: Boolean;
begin
  if  MLSpecialKeyComp(670) or
      MLSpecialKeyComp(1067) or
      MLSpecialKeyComp(1068) or
      MLSpecialKeyComp(1122) or
      MLSpecialKeyComp(1128) or
      MLSpecialKeyComp(1132) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc179: Boolean;
begin
  if  MLSpecialKeyComp(1121) or
      MLSpecialKeyComp(1467) or
      MLSpecialKeyComp(1698) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc180: Boolean;
begin
  if  MLSpecialKeyComp(856) or
      MLSpecialKeyComp(857) or
      MLSpecialKeyComp(858) or
      MLSpecialKeyComp(859) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc181: Boolean;
begin
  if  MLSpecialKeyComp(615) or
      MLSpecialKeyComp(1469) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc182: Boolean;
begin
  if  MLSpecialKeyComp(419) or
      MLSpecialKeyComp(851) or
      MLSpecialKeyComp(1489) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc184: Boolean;
begin
  if  MLSpecialKeyComp(874) or
      MLSpecialKeyComp(1193) or
      MLSpecialKeyComp(1483) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc185: Boolean;
begin
  if  MLSpecialKeyComp(614) or
      MLSpecialKeyComp(870) or
      MLSpecialKeyComp(892) or
      MLSpecialKeyComp(941) or
      MLSpecialKeyComp(942) or
      MLSpecialKeyComp(943) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc186: Boolean;
begin
  if  MLSpecialKeyComp(415) or
      MLSpecialKeyComp(541) or
      MLSpecialKeyComp(666) or
      MLSpecialKeyComp(854) or
      MLSpecialKeyComp(1475) or
      MLSpecialKeyComp(1853) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc187: Boolean;
begin
  if  MLSpecialKeyComp(244) or
      MLSpecialKeyComp(320) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc188: Boolean;
begin
  if  MLSpecialKeyComp(863) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc189: Boolean;
begin
  if  MLSpecialKeyComp(1895) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc190: Boolean;
begin
  if  MLSpecialKeyComp(396) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc191: Boolean;
begin
  if  MLSpecialKeyComp(953) or
      MLSpecialKeyComp(1145) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc192: Boolean;
begin
  if  MLSpecialKeyComp(280) or
      MLSpecialKeyComp(1066) or
      MLSpecialKeyComp(1580) or
      MLSpecialKeyComp(1647) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc193: Boolean;
begin
  if  MLSpecialKeyComp(872) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc194: Boolean;
begin
  if  MLSpecialKeyComp(1099) or
      MLSpecialKeyComp(1100) or
      MLSpecialKeyComp(1287) or
      MLSpecialKeyComp(1797) or
      MLSpecialKeyComp(1855) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc195: Boolean;
begin
  if  MLSpecialKeyComp(945) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc196: Boolean;
begin
  if  MLSpecialKeyComp(403) or
      MLSpecialKeyComp(618) or
      MLSpecialKeyComp(1836) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc197: Boolean;
begin
  if  MLSpecialKeyComp(1141) or
      MLSpecialKeyComp(1344) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc198: Boolean;
begin
  if  MLSpecialKeyComp(361) or
      MLSpecialKeyComp(1576) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc199: Boolean;
begin
  if  MLSpecialKeyComp(860) or
      MLSpecialKeyComp(1476) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc201: Boolean;
begin
  if  MLSpecialKeyComp(422) or
      MLSpecialKeyComp(1471) or
      MLSpecialKeyComp(1676) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc203: Boolean;
begin
  if  MLSpecialKeyComp(420) or
      MLSpecialKeyComp(852) or
      MLSpecialKeyComp(1490) or
      MLSpecialKeyComp(1917) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc204: Boolean;
begin
  if  MLSpecialKeyComp(1486) or
      MLSpecialKeyComp(1633) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc205: Boolean;
begin
  if  MLSpecialKeyComp(416) or
      MLSpecialKeyComp(1474) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc206: Boolean;
begin
  if  MLSpecialKeyComp(321) or
      MLSpecialKeyComp(414) or
      MLSpecialKeyComp(1151) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc207: Boolean;
begin
  if  MLSpecialKeyComp(1255) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc210: Boolean;
begin
  if  MLSpecialKeyComp(954) or
      MLSpecialKeyComp(1479) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc211: Boolean;
begin
  if  MLSpecialKeyComp(261) or
      MLSpecialKeyComp(861) or
      MLSpecialKeyComp(1477) or
      MLSpecialKeyComp(1575) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc212: Boolean;
begin
  if  MLSpecialKeyComp(418) or
      MLSpecialKeyComp(850) or
      MLSpecialKeyComp(1488) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc213: Boolean;
begin
  if  MLSpecialKeyComp(1798) or
      MLSpecialKeyComp(1856) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc215: Boolean;
begin
  if  MLSpecialKeyComp(1072) or
      MLSpecialKeyComp(1140) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc217: Boolean;
begin
  if  MLSpecialKeyComp(480) or
      MLSpecialKeyComp(1579) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc218: Boolean;
begin
  if  MLSpecialKeyComp(1478) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc219: Boolean;
begin
  if  MLSpecialKeyComp(871) or
      MLSpecialKeyComp(1116) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc222: Boolean;
begin
  if  MLSpecialKeyComp(423) or
      MLSpecialKeyComp(1472) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc223: Boolean;
begin
  if  MLSpecialKeyComp(1632) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc225: Boolean;
begin
  if  MLSpecialKeyComp(400) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc227: Boolean;
begin
  if  MLSpecialKeyComp(406) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc228: Boolean;
begin
  if  MLSpecialKeyComp(937) or
      MLSpecialKeyComp(938) or
      MLSpecialKeyComp(939) or
      MLSpecialKeyComp(1148) or
      MLSpecialKeyComp(1448) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc231: Boolean;
begin
  if  MLSpecialKeyComp(421) or
      MLSpecialKeyComp(1470) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc232: Boolean;
begin
  if  MLSpecialKeyComp(1630) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc234: Boolean;
begin
  if  MLSpecialKeyComp(1129) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc238: Boolean;
begin
  if  MLSpecialKeyComp(1487) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc239: Boolean;
begin
  if  MLSpecialKeyComp(398) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc243: Boolean;
begin
  if  MLSpecialKeyComp(412) or
      MLSpecialKeyComp(1847) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc244: Boolean;
begin
  if  MLSpecialKeyComp(402) or
      MLSpecialKeyComp(417) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc246: Boolean;
begin
  if  MLSpecialKeyComp(1139) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc248: Boolean;
begin
  if  MLSpecialKeyComp(1069) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc250: Boolean;
begin
  if  MLSpecialKeyComp(1147) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc251: Boolean;
begin
  if  MLSpecialKeyComp(394) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc253: Boolean;
begin
  if  MLSpecialKeyComp(862) or
      MLSpecialKeyComp(1142) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc255: Boolean;
begin
  if  MLSpecialKeyComp(846) or
      MLSpecialKeyComp(1466) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc256: Boolean;
begin
  if  MLSpecialKeyComp(542) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc260: Boolean;
begin
  if  MLSpecialKeyComp(1634) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc265: Boolean;
begin
  if  MLSpecialKeyComp(1449) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc266: Boolean;
begin
  if  MLSpecialKeyComp(1254) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc270: Boolean;
begin
  if  MLSpecialKeyComp(260) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc272: Boolean;
begin
  if  MLSpecialKeyComp(1143) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc287: Boolean;
begin
  if  MLSpecialKeyComp(401) or
      MLSpecialKeyComp(482) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc292: Boolean;
begin
  if  MLSpecialKeyComp(259) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc309: Boolean;
begin
  if  MLSpecialKeyComp(1144) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc388: Boolean;
begin
  if  MLSpecialKeyComp(288) then
    Result := True
  else
    Result := False;
end;
