function TSynWebEngine.MLAttrUndef: TSynWebTokenKind;
begin
  Result:=stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc13: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(79) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc15: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(58) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc23: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(0) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc26: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(42) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc27: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(29) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc30: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(21) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc31: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(50) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc32: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(73) or
      MLAttrKeyComp(84) or
      MLAttrKeyComp(98) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc33: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(7) or
      MLAttrKeyComp(103) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc34: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(85) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc35: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(199) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc36: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(100) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc37: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(25) or
      MLAttrKeyComp(74) or
      MLAttrKeyComp(101) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc38: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(49) or
      MLAttrKeyComp(96) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc39: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(24) or
      MLAttrKeyComp(28) or
      MLAttrKeyComp(59) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc40: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(219) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc41: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(78) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc42: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(80) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc43: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(5) or
      MLAttrKeyComp(68) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc44: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(72) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc45: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(189) or
      MLAttrKeyComp(201) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc46: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(87) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc47: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(6) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc48: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(1) or
      MLAttrKeyComp(43) or
      MLAttrKeyComp(48) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc49: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(33) or
      MLAttrKeyComp(214) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc50: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(92) or
      MLAttrKeyComp(185) or
      MLAttrKeyComp(217) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc52: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(60) or
      MLAttrKeyComp(76) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc53: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(13) or
      MLAttrKeyComp(207) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc54: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(26) or
      MLAttrKeyComp(30) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc55: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(110) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc56: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(51) or
      MLAttrKeyComp(52) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc57: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(22) or
      MLAttrKeyComp(53) or
      MLAttrKeyComp(71) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc58: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(81) or
      MLAttrKeyComp(91) or
      MLAttrKeyComp(208) or
      MLAttrKeyComp(239) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc59: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(122) or
      MLAttrKeyComp(215) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc60: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(70) or
      MLAttrKeyComp(88) or
      MLAttrKeyComp(223) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc61: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(67) or
      MLAttrKeyComp(131) or
      MLAttrKeyComp(144) or
      MLAttrKeyComp(233) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc62: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(4) or
      MLAttrKeyComp(9) or
      MLAttrKeyComp(16) or
      MLAttrKeyComp(209) or
      MLAttrKeyComp(220) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc63: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(32) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc64: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(238) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc65: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(99) or
      MLAttrKeyComp(232) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc66: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(8) or
      MLAttrKeyComp(46) or
      MLAttrKeyComp(57) or
      MLAttrKeyComp(105) or
      MLAttrKeyComp(107) or
      MLAttrKeyComp(229) or
      MLAttrKeyComp(230) or
      MLAttrKeyComp(237) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc67: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(20) or
      MLAttrKeyComp(27) or
      MLAttrKeyComp(118) or
      MLAttrKeyComp(119) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc68: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(86) or
      MLAttrKeyComp(160) or
      MLAttrKeyComp(236) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc69: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(188) or
      MLAttrKeyComp(196) or
      MLAttrKeyComp(228) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc70: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(82) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc71: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(36) or
      MLAttrKeyComp(55) or
      MLAttrKeyComp(75) or
      MLAttrKeyComp(167) or
      MLAttrKeyComp(193) or
      MLAttrKeyComp(227) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc72: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(15) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc73: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(62) or
      MLAttrKeyComp(212) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc74: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(23) or
      MLAttrKeyComp(41) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc75: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(203) or
      MLAttrKeyComp(205) or
      MLAttrKeyComp(231) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc77: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(47) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc78: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(171) or
      MLAttrKeyComp(216) or
      MLAttrKeyComp(222) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc79: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(90) or
      MLAttrKeyComp(206) or
      MLAttrKeyComp(226) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc80: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(34) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc81: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(194) or
      MLAttrKeyComp(224) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc82: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(115) or
      MLAttrKeyComp(123) or
      MLAttrKeyComp(128) or
      MLAttrKeyComp(242) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc83: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(89) or
      MLAttrKeyComp(161) or
      MLAttrKeyComp(181) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc84: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(157) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc85: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(111) or
      MLAttrKeyComp(121) or
      MLAttrKeyComp(221) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc87: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(18) or
      MLAttrKeyComp(93) or
      MLAttrKeyComp(109) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc88: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(56) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc91: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(3) or
      MLAttrKeyComp(37) or
      MLAttrKeyComp(159) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc93: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(31) or
      MLAttrKeyComp(135) or
      MLAttrKeyComp(173) or
      MLAttrKeyComp(192) or
      MLAttrKeyComp(211) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc94: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(174) or
      MLAttrKeyComp(179) or
      MLAttrKeyComp(190) or
      MLAttrKeyComp(198) or
      MLAttrKeyComp(218) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc96: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(14) or
      MLAttrKeyComp(145) or
      MLAttrKeyComp(155) or
      MLAttrKeyComp(168) or
      MLAttrKeyComp(182) or
      MLAttrKeyComp(202) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc97: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(35) or
      MLAttrKeyComp(200) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc98: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(148) or
      MLAttrKeyComp(156) or
      MLAttrKeyComp(195) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc99: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(172) or
      MLAttrKeyComp(191) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc100: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(140) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc101: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(19) or
      MLAttrKeyComp(116) or
      MLAttrKeyComp(130) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc102: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(175) or
      MLAttrKeyComp(187) or
      MLAttrKeyComp(235) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc103: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(108) or
      MLAttrKeyComp(134) or
      MLAttrKeyComp(138) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc104: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(97) or
      MLAttrKeyComp(125) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc105: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(54) or
      MLAttrKeyComp(69) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc106: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(204) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc107: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(83) or
      MLAttrKeyComp(143) or
      MLAttrKeyComp(186) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc108: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(102) or
      MLAttrKeyComp(170) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc109: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(139) or
      MLAttrKeyComp(210) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc110: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(225) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc111: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(12) or
      MLAttrKeyComp(106) or
      MLAttrKeyComp(165) or
      MLAttrKeyComp(169) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc112: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(184) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc113: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(162) or
      MLAttrKeyComp(177) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc114: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(45) or
      MLAttrKeyComp(61) or
      MLAttrKeyComp(176) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc116: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(40) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc117: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(64) or
      MLAttrKeyComp(213) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc119: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(44) or
      MLAttrKeyComp(94) or
      MLAttrKeyComp(126) or
      MLAttrKeyComp(136) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc121: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(11) or
      MLAttrKeyComp(124) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc122: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(240) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc123: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(66) or
      MLAttrKeyComp(158) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc124: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(197) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc126: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(95) or
      MLAttrKeyComp(141) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc127: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(178) or
      MLAttrKeyComp(234) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc132: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(241) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc135: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(146) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc137: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(127) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc139: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(147) or
      MLAttrKeyComp(153) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc140: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(63) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc141: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(163) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc143: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(104) or
      MLAttrKeyComp(180) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc146: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(10) or
      MLAttrKeyComp(164) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc147: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(114) or
      MLAttrKeyComp(142) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc149: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(38) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc154: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(39) or
      MLAttrKeyComp(132) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc155: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(17) or
      MLAttrKeyComp(65) or
      MLAttrKeyComp(154) or
      MLAttrKeyComp(183) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc156: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(112) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc157: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(113) or
      MLAttrKeyComp(150) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc158: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(149) or
      MLAttrKeyComp(151) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc160: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(2) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc161: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(137) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc162: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(152) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc169: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(129) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc176: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(77) or
      MLAttrKeyComp(133) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc183: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(120) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc185: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(166) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc198: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(117) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;
