function TSynWebEngine.CssValUndef: TSynWebTokenKind;
begin
  Result:=stkCssValUndef;
end;

function TSynWebEngine.CssValFunc26: TSynWebTokenKind;
begin
  if  CssValKeyComp(59) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc27: TSynWebTokenKind;
begin
  if  CssValKeyComp(28) or
      CssValKeyComp(125) or
      CssValKeyComp(130) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc29: TSynWebTokenKind;
begin
  if  CssValKeyComp(12) or
      CssValKeyComp(43) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc31: TSynWebTokenKind;
begin
  if  CssValKeyComp(91) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc32: TSynWebTokenKind;
begin
  if  CssValKeyComp(60) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc33: TSynWebTokenKind;
begin
  if  CssValKeyComp(16) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc35: TSynWebTokenKind;
begin
  if  CssValKeyComp(40) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc36: TSynWebTokenKind;
begin
  if  CssValKeyComp(25) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc37: TSynWebTokenKind;
begin
  if  CssValKeyComp(112) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc38: TSynWebTokenKind;
begin
  if  CssValKeyComp(170) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc39: TSynWebTokenKind;
begin
  if  CssValKeyComp(79) or
      CssValKeyComp(119) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc40: TSynWebTokenKind;
begin
  if  CssValKeyComp(3) or
      CssValKeyComp(15) or
      CssValKeyComp(161) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc41: TSynWebTokenKind;
begin
  if  CssValKeyComp(35) or
      CssValKeyComp(57) or
      CssValKeyComp(62) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc42: TSynWebTokenKind;
begin
  if  CssValKeyComp(9) or
      CssValKeyComp(50) or
      CssValKeyComp(158) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc43: TSynWebTokenKind;
begin
  if  CssValKeyComp(14) or
      CssValKeyComp(72) or
      CssValKeyComp(74) or
      CssValKeyComp(131) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc44: TSynWebTokenKind;
begin
  if  CssValKeyComp(58) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc45: TSynWebTokenKind;
begin
  if  CssValKeyComp(0) or
      CssValKeyComp(18) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc46: TSynWebTokenKind;
begin
  if  CssValKeyComp(48) or
      CssValKeyComp(97) or
      CssValKeyComp(124) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc47: TSynWebTokenKind;
begin
  if  CssValKeyComp(36) or
      CssValKeyComp(96) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc48: TSynWebTokenKind;
begin
  if  CssValKeyComp(13) or
      CssValKeyComp(51) or
      CssValKeyComp(103) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc49: TSynWebTokenKind;
begin
  if  CssValKeyComp(55) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc50: TSynWebTokenKind;
begin
  if  CssValKeyComp(26) or
      CssValKeyComp(83) or
      CssValKeyComp(90) or
      CssValKeyComp(135) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc51: TSynWebTokenKind;
begin
  if  CssValKeyComp(7) or
      CssValKeyComp(54) or
      CssValKeyComp(174) or
      CssValKeyComp(175) or
      CssValKeyComp(176) or
      CssValKeyComp(183) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc52: TSynWebTokenKind;
begin
  if  CssValKeyComp(82) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc53: TSynWebTokenKind;
begin
  if  CssValKeyComp(94) or
      CssValKeyComp(185) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc54: TSynWebTokenKind;
begin
  if  CssValKeyComp(70) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc55: TSynWebTokenKind;
begin
  if  CssValKeyComp(61) or
      CssValKeyComp(99) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc56: TSynWebTokenKind;
begin
  if  CssValKeyComp(17) or
      CssValKeyComp(77) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc57: TSynWebTokenKind;
begin
  if  CssValKeyComp(6) or
      CssValKeyComp(10) or
      CssValKeyComp(141) or
      CssValKeyComp(147) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc59: TSynWebTokenKind;
begin
  if  CssValKeyComp(5) or
      CssValKeyComp(42) or
      CssValKeyComp(152) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc60: TSynWebTokenKind;
begin
  if  CssValKeyComp(68) or
      CssValKeyComp(114) or
      CssValKeyComp(151) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc61: TSynWebTokenKind;
begin
  if  CssValKeyComp(73) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc62: TSynWebTokenKind;
begin
  if  CssValKeyComp(100) or
      CssValKeyComp(132) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc63: TSynWebTokenKind;
begin
  if  CssValKeyComp(64) or
      CssValKeyComp(111) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc65: TSynWebTokenKind;
begin
  if  CssValKeyComp(22) or
      CssValKeyComp(93) or
      CssValKeyComp(127) or
      CssValKeyComp(142) or
      CssValKeyComp(186) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc67: TSynWebTokenKind;
begin
  if  CssValKeyComp(8) or
      CssValKeyComp(52) or
      CssValKeyComp(67) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc68: TSynWebTokenKind;
begin
  if  CssValKeyComp(39) or
      CssValKeyComp(41) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc69: TSynWebTokenKind;
begin
  if  CssValKeyComp(38) or
      CssValKeyComp(49) or
      CssValKeyComp(145) or
      CssValKeyComp(171) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc72: TSynWebTokenKind;
begin
  if  CssValKeyComp(156) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc73: TSynWebTokenKind;
begin
  if  CssValKeyComp(84) or
      CssValKeyComp(106) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc75: TSynWebTokenKind;
begin
  if  CssValKeyComp(4) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc76: TSynWebTokenKind;
begin
  if  CssValKeyComp(53) or
      CssValKeyComp(92) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc78: TSynWebTokenKind;
begin
  if  CssValKeyComp(21) or
      CssValKeyComp(184) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc79: TSynWebTokenKind;
begin
  if  CssValKeyComp(78) or
      CssValKeyComp(138) or
      CssValKeyComp(143) or
      CssValKeyComp(159) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc80: TSynWebTokenKind;
begin
  if  CssValKeyComp(150) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc81: TSynWebTokenKind;
begin
  if  CssValKeyComp(2) or
      CssValKeyComp(110) or
      CssValKeyComp(154) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc82: TSynWebTokenKind;
begin
  if  CssValKeyComp(56) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc83: TSynWebTokenKind;
begin
  if  CssValKeyComp(29) or
      CssValKeyComp(63) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc85: TSynWebTokenKind;
begin
  if  CssValKeyComp(19) or
      CssValKeyComp(139) or
      CssValKeyComp(144) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc86: TSynWebTokenKind;
begin
  if  CssValKeyComp(45) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc87: TSynWebTokenKind;
begin
  if  CssValKeyComp(107) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc88: TSynWebTokenKind;
begin
  if  CssValKeyComp(69) or
      CssValKeyComp(123) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc92: TSynWebTokenKind;
begin
  if  CssValKeyComp(126) or
      CssValKeyComp(146) or
      CssValKeyComp(198) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc93: TSynWebTokenKind;
begin
  if  CssValKeyComp(116) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc94: TSynWebTokenKind;
begin
  if  CssValKeyComp(189) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc95: TSynWebTokenKind;
begin
  if  CssValKeyComp(1) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc96: TSynWebTokenKind;
begin
  if  CssValKeyComp(31) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc97: TSynWebTokenKind;
begin
  if  CssValKeyComp(34) or
      CssValKeyComp(118) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc100: TSynWebTokenKind;
begin
  if  CssValKeyComp(115) or
      CssValKeyComp(117) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc101: TSynWebTokenKind;
begin
  if  CssValKeyComp(86) or
      CssValKeyComp(98) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc102: TSynWebTokenKind;
begin
  if  CssValKeyComp(20) or
      CssValKeyComp(178) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc104: TSynWebTokenKind;
begin
  if  CssValKeyComp(180) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc105: TSynWebTokenKind;
begin
  if  CssValKeyComp(190) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc106: TSynWebTokenKind;
begin
  if  CssValKeyComp(46) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc108: TSynWebTokenKind;
begin
  if  CssValKeyComp(76) or
      CssValKeyComp(188) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc110: TSynWebTokenKind;
begin
  if  CssValKeyComp(33) or
      CssValKeyComp(71) or
      CssValKeyComp(163) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc112: TSynWebTokenKind;
begin
  if  CssValKeyComp(192) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc114: TSynWebTokenKind;
begin
  if  CssValKeyComp(136) or
      CssValKeyComp(191) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc115: TSynWebTokenKind;
begin
  if  CssValKeyComp(32) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc117: TSynWebTokenKind;
begin
  if  CssValKeyComp(120) or
      CssValKeyComp(122) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc118: TSynWebTokenKind;
begin
  if  CssValKeyComp(75) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc119: TSynWebTokenKind;
begin
  if  CssValKeyComp(194) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc122: TSynWebTokenKind;
begin
  if  CssValKeyComp(195) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc125: TSynWebTokenKind;
begin
  if  CssValKeyComp(44) or
      CssValKeyComp(47) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc127: TSynWebTokenKind;
begin
  if  CssValKeyComp(128) or
      CssValKeyComp(134) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc128: TSynWebTokenKind;
begin
  if  CssValKeyComp(129) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc129: TSynWebTokenKind;
begin
  if  CssValKeyComp(196) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc131: TSynWebTokenKind;
begin
  if  CssValKeyComp(193) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc132: TSynWebTokenKind;
begin
  if  CssValKeyComp(105) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc134: TSynWebTokenKind;
begin
  if  CssValKeyComp(108) or
      CssValKeyComp(148) or
      CssValKeyComp(168) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc135: TSynWebTokenKind;
begin
  if  CssValKeyComp(121) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc137: TSynWebTokenKind;
begin
  if  CssValKeyComp(133) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc139: TSynWebTokenKind;
begin
  if  CssValKeyComp(101) or
      CssValKeyComp(155) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc141: TSynWebTokenKind;
begin
  if  CssValKeyComp(66) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc143: TSynWebTokenKind;
begin
  if  CssValKeyComp(187) or
      CssValKeyComp(197) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc144: TSynWebTokenKind;
begin
  if  CssValKeyComp(65) or
      CssValKeyComp(140) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc145: TSynWebTokenKind;
begin
  if  CssValKeyComp(81) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc146: TSynWebTokenKind;
begin
  if  CssValKeyComp(23) or
      CssValKeyComp(177) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc148: TSynWebTokenKind;
begin
  if  CssValKeyComp(95) or
      CssValKeyComp(137) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc149: TSynWebTokenKind;
begin
  if  CssValKeyComp(85) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc151: TSynWebTokenKind;
begin
  if  CssValKeyComp(30) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc152: TSynWebTokenKind;
begin
  if  CssValKeyComp(179) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc156: TSynWebTokenKind;
begin
  if  CssValKeyComp(162) or
      CssValKeyComp(164) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc157: TSynWebTokenKind;
begin
  if  CssValKeyComp(87) or
      CssValKeyComp(109) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc158: TSynWebTokenKind;
begin
  if  CssValKeyComp(11) or
      CssValKeyComp(153) or
      CssValKeyComp(173) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc159: TSynWebTokenKind;
begin
  if  CssValKeyComp(157) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc162: TSynWebTokenKind;
begin
  if  CssValKeyComp(160) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc165: TSynWebTokenKind;
begin
  if  CssValKeyComp(24) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc166: TSynWebTokenKind;
begin
  if  CssValKeyComp(113) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc167: TSynWebTokenKind;
begin
  if  CssValKeyComp(88) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc170: TSynWebTokenKind;
begin
  if  CssValKeyComp(27) or
      CssValKeyComp(181) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc172: TSynWebTokenKind;
begin
  if  CssValKeyComp(89) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc173: TSynWebTokenKind;
begin
  if  CssValKeyComp(149) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc175: TSynWebTokenKind;
begin
  if  CssValKeyComp(80) or
      CssValKeyComp(182) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc192: TSynWebTokenKind;
begin
  if  CssValKeyComp(172) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc233: TSynWebTokenKind;
begin
  if  CssValKeyComp(104) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc234: TSynWebTokenKind;
begin
  if  CssValKeyComp(167) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc237: TSynWebTokenKind;
begin
  if  CssValKeyComp(102) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc239: TSynWebTokenKind;
begin
  if  CssValKeyComp(37) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc249: TSynWebTokenKind;
begin
  if  CssValKeyComp(169) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc271: TSynWebTokenKind;
begin
  if  CssValKeyComp(165) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc272: TSynWebTokenKind;
begin
  if  CssValKeyComp(166) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;
